/* SelfLearn Class 8 pilot. Original bilingual lessons; see study-material/MATH8-PILOT.md.
   Chapter numbers are SelfLearn units, not a claim of identical JAC/CBSE sequencing. */
window.SL_DATA = window.SL_DATA || {subjects:[], questions:[]};
(function () {
  'use strict';
  function b(en, hi) { return {en:en, hi:hi}; }
  var topics = [];
  function lesson(n, name, notes, audio, example, steps, answer) {
    topics.push({code:'M8-1-'+n, name:name, notes:notes, audio:audio, audioPlayer:true,
      worked:[{title:b('Let’s work it out','आइए, मिलकर हल करें'), problem:example,
        steps:steps.map(function(s){return {do:b(s[0],s[1]),why:b(s[2],s[3])};}),answer:answer}]});
  }
  lesson(1, b('1. Make a square with tiles','1. टाइलों से square बनाइए'), b(
    '**A courtyard puzzle**\nRani is planning a small square patch in her school courtyard. She puts 4 tiles in each row. How many rows will make a square? Tell someone your guess.\n\n{{diagram:m8-square}}\n\n**Look, then count**\nFour rows of 4 tiles use 4 × 4 = 16 tiles. A square has equal side lengths. A 4-by-5 rectangle uses 20 tiles, but it is not a square.\n\nWe write 4 × 4 as **4²**, read “four squared”. The small 2 means multiply 4 by itself. It does not mean 4 × 2.\n\n**Try and explain**\nSet the side to 3, then 6. The side doubles, but the area changes from 9 to 36: four times as much! Can you see four small squares inside the large one?\n\n**Where it helps**\nFor a square with side 7 m, area = 7 × 7 = 49 m². Perimeter is different: it is the length around the edge, 4 × 7 = 28 m.\n\n**Remember**\nSide × side gives area, not perimeter. A whole number made by squaring a whole number is a perfect square; 0 is included here because 0² = 0.\n\n**Before practice**\nDraw a 5-by-5 square. Explain why it contains 25, not 10, unit squares.',
    '**स्कूल के आँगन की बात**\nरानी स्कूल के आँगन में square आकार की जगह बनाना चाहती है। हर पंक्ति में 4 टाइलें हैं। कितनी पंक्तियाँ होंगी? पहले अपना अंदाज़ा किसी को बताइए।\n\n{{diagram:m8-square}}\n\n**देखिए, फिर गिनिए**\n4 टाइलों की 4 पंक्तियों में 4 × 4 = 16 टाइलें हैं। Square की दोनों दिशाओं में लंबाई बराबर होती है। 4-by-5 rectangle में 20 टाइलें हैं, लेकिन वह square नहीं है।\n\n4 × 4 को **4²** लिखते हैं और “चार का वर्ग” कहते हैं। छोटा 2 बताता है कि 4 को उसी से गुणा करना है। इसका मतलब 4 × 2 नहीं है।\n\n**बदलकर समझाइए**\nSide पहले 3, फिर 6 कीजिए। Side दोगुनी हुई, लेकिन area 9 से 36 हो गया: चार गुना! बड़े square में चार छोटे square ढूँढिए।\n\n**कहाँ काम आएगा?**\n7 m side वाले square का area 7 × 7 = 49 m² है। Perimeter अलग है: चारों ओर की कुल लंबाई, यानी 4 × 7 = 28 m।\n\n**याद रखिए**\nSide × side से area मिलता है, perimeter नहीं। किसी whole number का square, perfect square है। यहाँ 0 भी शामिल है, क्योंकि 0² = 0।\n\n**अभ्यास से पहले**\n5-by-5 square बनाइए। समझाइए कि उसमें 25 छोटी इकाइयाँ क्यों हैं, 10 क्यों नहीं।'), b(
    'Imagine Rani laying tiles in the school courtyard. There are four tiles across. To make a square, she needs four equal rows. Count four, eight, twelve, sixteen. That is four multiplied by four.\n\nWe shorten this to four squared. The little two does not tell us to double four. It tells us to use four twice as a factor. Try the slider at three. You should see nine tiles.\n\nNow move to six. Before counting, predict: will the area double? It becomes thirty-six, which is four times nine. Doubling both directions makes four copies of the old square.\n\nArea counts the surface inside. Perimeter measures the boundary around it. For a side of five metres, the area is twenty-five square metres, but the perimeter is twenty metres. Pause and explain that difference in your own words.',
    'सोचिए, रानी स्कूल के आँगन में टाइलें लगा रही है। एक पंक्ति में चार टाइलें हैं। Square बनाने के लिए ऐसी चार पंक्तियाँ चाहिए। गिनिए: चार, आठ, बारह, सोलह। यानी चार गुणा चार।\n\nइसे छोटा करके चार का वर्ग कहते हैं। छोटा दो देखकर चार को दोगुना मत कीजिए। चार को उसी चार से गुणा करना है। Slider को तीन पर रखिए। नौ टाइलें दिखेंगी।\n\nअब छह पर जाने से पहले अंदाज़ा लगाइए। Area कितना होगा? छत्तीस। यह नौ का चार गुना है। दोनों दिशाओं में लंबाई दोगुनी करने से पुराने square की चार copies बन जाती हैं।\n\nArea अंदर की जगह है। Perimeter बाहर की पूरी सीमा की लंबाई है। पाँच मीटर side पर area पच्चीस square metre, लेकिन perimeter बीस metre होगा। रुककर यह अंतर अपने शब्दों में बताइए।'),
    b('A square rangoli has 8 dots in each row. How many dots are there?','Square रंगोली में हर पंक्ति में 8 बिंदु हैं। कुल कितने बिंदु हैं?'),
    [['There are 8 equal rows.','8 बराबर पंक्तियाँ हैं।','A square has the same count in both directions.','Square में दोनों दिशाओं में गिनती बराबर है।'],['8 × 8 = 64.','8 × 8 = 64।','Multiply rows by dots per row.','पंक्तियों को हर पंक्ति के बिंदुओं से गुणा कीजिए।']],b('64 dots.','64 बिंदु।'));

  lesson(2,b('2. Grow a square: odd-number patterns','2. Square बढ़ाइए: विषम संख्याओं का pattern'),b(
    '**One more row, one more column**\nRani wants to grow her 4-by-4 pattern into 5-by-5. Must she start again? Predict how many extra tiles she needs.\n\n{{diagram:m8-pattern}}\n\n**Notice the coloured border**\nAdd a column of 4, a row of 4, and the missing corner: 4 + 4 + 1 = 9. So 5² − 4² = 9. In general, growing side n to n + 1 adds 2n + 1 tiles, an odd number.\n\nStarting with 1 tile, add 3, then 5, then 7. The totals are 1, 4, 9, 16. The first n positive odd numbers add to n².\n\n**A useful detective rule**\nWhole-number squares end only in 0, 1, 4, 5, 6 or 9. A number ending in 2, 3, 7 or 8 cannot be a square. But an allowed ending is only a clue: 26 ends in 6 and is not a square.\n\nEven numbers have even squares; odd numbers have odd squares. A positive perfect square has an even number of trailing zeros: 100 has two, 10000 has four.\n\n**Think and apply**\nBetween 4² = 16 and 5² = 25 there are 8 whole numbers, 17 through 24. The gap is 9, but the count strictly between is 8. Explain the difference before practice.',
    '**एक पंक्ति और एक column**\nरानी 4-by-4 pattern को 5-by-5 करना चाहती है। क्या सब फिर से बनाना पड़ेगा? पहले बताइए, कितनी नई टाइलें चाहिए?\n\n{{diagram:m8-pattern}}\n\n**रंगीन किनारा देखिए**\n4 का एक column, 4 की एक पंक्ति और कोने की 1 टाइल जोड़िए: 4 + 4 + 1 = 9। इसलिए 5² − 4² = 9। Side n से n + 1 करने पर 2n + 1 टाइलें बढ़ती हैं। यह हमेशा odd, यानी विषम संख्या है।\n\n1 टाइल से शुरू करके 3, फिर 5, फिर 7 जोड़िए। कुल 1, 4, 9, 16 मिलते हैं। पहली n धनात्मक odd संख्याओं का जोड़ n² है।\n\n**संख्या पहचानने का संकेत**\nWhole-number square का आखिरी digit सिर्फ 0, 1, 4, 5, 6 या 9 हो सकता है। 2, 3, 7 या 8 पर खत्म होने वाली संख्या square नहीं होगी। लेकिन सही ending होना प्रमाण नहीं है: 26 के अंत में 6 है, फिर भी वह square नहीं है।\n\nEven संख्या का square even और odd का square odd होता है। धनात्मक perfect square के अंत में zeros की संख्या even होती है: 100 में दो, 10000 में चार।\n\n**सोचकर लगाइए**\n4² = 16 और 5² = 25 के बीच 17 से 24 तक 8 whole numbers हैं। अंतर 9 है, लेकिन बीच की संख्याएँ 8 हैं। दोनों बातों का अंतर समझाइए।'),b(
    'Keep the old four-by-four square. Add four tiles along one edge and four along the next. Is the new square complete? Not yet: its corner needs one more tile. We added nine, not eight.\n\nTry a smaller square. From two-by-two to three-by-three, add two plus two plus one: five. These odd borders explain why one plus three plus five makes nine.\n\nNow a warning. A number ending in eight cannot be a whole-number square. But a number ending in six might be a square or might not. Sixteen works; twenty-six does not. A clue is not a proof.\n\nBetween sixteen and twenty-five the difference is nine, but only eight whole numbers lie strictly between. Do not count the endpoints. Try growing a six-by-six pattern and predict the new border before moving the slider.',
    'पुराना चार-by-चार square रहने दीजिए। एक किनारे पर चार और दूसरे पर चार टाइलें लगाइए। क्या नया square पूरा हुआ? अभी कोने में एक टाइल कम है। कुल नौ जोड़नी पड़ीं, आठ नहीं।\n\nदो-by-दो से तीन-by-तीन बनाइए। दो और दो और एक, यानी पाँच नई टाइलें। इन odd किनारों से समझ आता है कि एक जोड़ तीन जोड़ पाँच, नौ क्यों होता है।\n\nअब ध्यान दीजिए। आठ पर खत्म होने वाली whole number square नहीं हो सकती। लेकिन छह पर खत्म होने से square होना पक्का नहीं होता। सोलह square है, छब्बीस नहीं। संकेत और प्रमाण अलग बातें हैं।\n\nसोलह और पच्चीस का अंतर नौ है। लेकिन उनके बीच सिर्फ आठ whole numbers हैं। दोनों सिरों को नहीं गिनना है। अब छह-by-छह का pattern बढ़ाने से पहले नए किनारे की टाइलों का अंदाज़ा लगाइए।'),
    b('How many tiles extend a 7-by-7 square to 8-by-8?','7-by-7 को 8-by-8 बनाने के लिए कितनी नई टाइलें चाहिए?'),
    [['Add 7 + 7 + 1.','7 + 7 + 1 जोड़िए।','Two strips and their corner complete the border.','दो पट्टियाँ और उनका कोना नया किनारा पूरा करते हैं।'],['7 + 7 + 1 = 15; also 64 − 49 = 15.','7 + 7 + 1 = 15; और 64 − 49 = 15।','Count and subtraction agree.','गिनती और घटाने से एक ही उत्तर मिला।']],b('15 extra tiles.','15 नई टाइलें।'));

  lesson(3,b('3. Square roots: find the side','3. Square root: side खोजिए'),b(
    '**Work backwards**\nA square patch contains 49 unit tiles. Rani knows the total, but not the number along one side. What number multiplied by itself gives 49?\n\n{{diagram:m8-root}}\n\n**Undo the square**\n7 × 7 = 49, so √49 = 7. The symbol √ asks for the non-negative square root. Squaring travels from side to area; square root travels from area to side. It is not “divide by 2”.\n\n**A small but important distinction**\n(−7)² is also 49. So the equation x² = 49 has two solutions, 7 and −7. But √49 means just 7. A physical side length cannot be negative.\n\n**Smaller than one is allowed**\nA square of side 0.5 m has area 0.25 m², because 0.5 × 0.5 = 0.25. Therefore √0.25 = 0.5. Also √(9/16) = 3/4, since (3/4) × (3/4) = 9/16.\n\n**Try it**\nUse the slider to make an area of 81. Before reading the side, predict it. Then check by multiplying your answer by itself.\n\n**Remember and reflect**\nThe root of an area in m² is a length in m. Explain why a square with area 64 m² has side 8 m, not 32 m.',
    '**अब उल्टी दिशा में सोचिए**\nSquare जगह में 49 unit टाइलें हैं। रानी को कुल टाइलें मालूम हैं, लेकिन एक side पर कितनी हैं? कौन-सी संख्या को उसी से गुणा करने पर 49 आता है?\n\n{{diagram:m8-root}}\n\n**Square को उल्टा कीजिए**\n7 × 7 = 49, इसलिए √49 = 7। √ का मतलब non-negative square root है। Squaring में side से area मिलता है। Square root में area से side मिलती है। यह “2 से भाग देना” नहीं है।\n\n**एक छोटा, ज़रूरी अंतर**\n(−7)² भी 49 है। इसलिए x² = 49 के दो हल हैं: 7 और −7। लेकिन √49 का मतलब सिर्फ 7 है। असली side की लंबाई negative नहीं हो सकती।\n\n**एक से छोटा भी हो सकता है**\n0.5 m side वाले square का area 0.25 m² है, क्योंकि 0.5 × 0.5 = 0.25। इसलिए √0.25 = 0.5। इसी तरह √(9/16) = 3/4, क्योंकि (3/4) × (3/4) = 9/16।\n\n**ख़ुद करके देखिए**\nSlider से area 81 बनाइए। Side पढ़ने से पहले अंदाज़ा लगाइए। अपने उत्तर को उसी से गुणा करके जाँचिए।\n\n**याद रखिए और समझाइए**\nm² में दिए area का root, m में लंबाई है। 64 m² वाले square की side 8 m क्यों है, 32 m क्यों नहीं?'),b(
    'This time we know the total: forty-nine tiles. We need equal rows with the same number of tiles in each row. Seven rows of seven work, so the square root of forty-nine is seven.\n\nDo not divide forty-nine by two. Instead ask: what number times itself gives forty-nine? The square root reverses a square.\n\nYou might notice that negative seven times negative seven is also forty-nine. That is true. The equation x squared equals forty-nine has two solutions. But the square root sign asks for the non-negative one, seven.\n\nRoots can be fractions too. Half a metre times half a metre is a quarter of a square metre. So the square root of zero point two five is zero point five. Check a root by squaring it. That check works every time.',
    'इस बार कुल उनचास टाइलें मालूम हैं। बराबर पंक्तियाँ चाहिए और हर पंक्ति में उतनी ही टाइलें। सात की सात पंक्तियाँ सही बैठती हैं। इसलिए उनचास का square root सात है।\n\nउनचास को दो से भाग नहीं देना है। पूछिए: कौन-सी संख्या खुद से गुणा होकर उनचास देगी? Square root, square करने की उल्टी क्रिया है।\n\nआप कह सकते हैं कि ऋण सात गुणा ऋण सात भी उनचास है। सही बात है। एक्स का square बराबर उनचास वाले equation के दो हल हैं। लेकिन root का चिन्ह non-negative वाला उत्तर माँगता है: सात।\n\nRoot fraction भी हो सकता है। आधा metre गुणा आधा metre, एक चौथाई square metre है। इसलिए शून्य दशमलव दो पाँच का root, शून्य दशमलव पाँच है। Root की जाँच उसे खुद से गुणा करके कीजिए।'),
    b('A square mat has area 2.25 m². Find its side.','Square चटाई का area 2.25 m² है। Side खोजिए।'),
    [['15 × 15 = 225.','15 × 15 = 225।','Start with a familiar whole-number square.','पहले जाना-पहचाना whole-number square लीजिए।'],['1.5 × 1.5 = 2.25.','1.5 × 1.5 = 2.25।','Check the decimal position by multiplication.','गुणा करके decimal की जगह जाँचिए।']],b('The side is 1.5 m.','Side 1.5 m है।'));

  lesson(4,b('4. Prime pairs reveal square roots','4. Prime जोड़ियों से square root'),b(
    '**A bigger tile order**\nThe school receives 144 tiles. You need not try every possible side length. Can smaller factors help?\n\n{{diagram:m8-pairs}}\n\n**Break down, then pair up**\n144 = 2 × 2 × 2 × 2 × 3 × 3. Group equal primes: (2 × 2)(2 × 2)(3 × 3). One factor from each pair goes into the root: 2 × 2 × 3 = 12. Check: 12² = 144.\n\nWhy one per pair? Each pair is itself a square. The root takes one copy; squaring puts the second copy back.\n\n**What if a factor is left alone?**\n72 = (2 × 2)(3 × 3) × 2. The last 2 has no partner, so 72 is not a perfect square. Multiply by 2 to make 144. Or divide by 2 to make 36. Here 2 is the smallest positive whole number that works for either operation.\n\n**Avoid this trap**\nDo not add the factors you pick: 2 + 2 + 3 is not the root. Multiply them. Also, pairing different primes such as 2 and 3 does not make a square.\n\n**Try and reflect**\nChoose 180 in the lab. Which factor has no partner? Explain why multiplying by 5 makes a square. This helps plan complete square arrangements without guessing.',
    '**टाइलों का बड़ा order**\nस्कूल में 144 टाइलें आई हैं। हर side का अंदाज़ा लगाने की ज़रूरत नहीं। क्या छोटे factors मदद करेंगे?\n\n{{diagram:m8-pairs}}\n\n**छोटे factors बनाइए, फिर जोड़ी लगाइए**\n144 = 2 × 2 × 2 × 2 × 3 × 3। बराबर primes की जोड़ियाँ बनाइए: (2 × 2)(2 × 2)(3 × 3)। हर जोड़ी से एक factor लीजिए: 2 × 2 × 3 = 12। जाँच: 12² = 144।\n\nहर जोड़ी से एक ही क्यों? जोड़ी खुद एक square है। Root एक copy लेता है। Square करने पर दूसरी copy फिर आ जाती है।\n\n**कोई factor अकेला बच जाए तो?**\n72 = (2 × 2)(3 × 3) × 2। आखिरी 2 का साथी नहीं है, इसलिए 72 perfect square नहीं है। 2 से गुणा करें तो 144 मिलता है। या 2 से भाग करें तो 36 मिलता है। यहाँ दोनों कामों के लिए सबसे छोटी धनात्मक whole number 2 है।\n\n**इस भूल से बचिए**\nचुने हुए factors को जोड़ना नहीं है: 2 + 2 + 3 root नहीं है। उन्हें गुणा कीजिए। 2 और 3 जैसे अलग primes की जोड़ी भी square नहीं बनाती।\n\n**करके समझाइए**\nLab में 180 चुनिए। कौन-सा factor अकेला है? 5 से गुणा करने पर square क्यों बनेगा? बड़ी square व्यवस्था बनाने में यह तरीका अंदाज़े से बेहतर है।'),b(
    'Let us find the side for one hundred and forty-four tiles. Break the number into prime factors: four twos and two threes. Make pairs of equal primes. You have two pairs of twos and one pair of threes.\n\nChoose one number from each pair and multiply: two times two times three is twelve. Why does this work? When twelve is squared, every chosen factor appears twice again.\n\nTry seventy-two. Its factors make a pair of twos, a pair of threes, and one lonely two. That lonely factor tells us seventy-two is not a perfect square.\n\nWe can supply its partner by multiplying by two. Or remove the lonely factor by dividing by two. The results are one hundred and forty-four and thirty-six. Both are squares. Remember: pair equal primes, then multiply one from each pair.',
    'एक सौ चवालीस टाइलों के लिए side खोजते हैं। Prime factors बनाइए: चार बार दो और दो बार तीन। बराबर primes की जोड़ी बनाइए। दो की दो जोड़ियाँ और तीन की एक जोड़ी मिलेगी।\n\nहर जोड़ी से एक संख्या लेकर गुणा कीजिए। दो गुणा दो गुणा तीन, बारह है। तरीका काम क्यों करता है? बारह का square करने पर हर चुना factor फिर दो बार आ जाता है।\n\nअब बहत्तर लीजिए। इसमें दो की एक जोड़ी, तीन की एक जोड़ी और एक अकेला दो है। यह अकेला factor बताता है कि बहत्तर perfect square नहीं है।\n\nदो से गुणा करके उसका साथी जोड़ सकते हैं। या दो से भाग देकर अकेला factor हटा सकते हैं। उत्तर एक सौ चवालीस और छत्तीस हैं। दोनों square हैं। बराबर primes की जोड़ी बनाइए, फिर हर जोड़ी से एक लेकर गुणा कीजिए।'),
    b('Find √196 using prime pairs.','Prime जोड़ियों से √196 खोजिए।'),
    [['196 = (2 × 2)(7 × 7).','196 = (2 × 2)(7 × 7)।','Every prime factor has a partner.','हर prime factor का साथी है।'],['√196 = 2 × 7 = 14.','√196 = 2 × 7 = 14।','Take one factor from each pair.','हर जोड़ी से एक factor लीजिए।']],b('14; check 14 × 14 = 196.','14; जाँचिए 14 × 14 = 196।'));

  lesson(5,b('5. Estimate before calculating','5. हिसाब से पहले अंदाज़ा'),b(
    '**Will a 7 m side be enough?**\nA square garden must cover 50 m². A 7 m side gives only 49 m². An 8 m side gives 64 m². The exact side lies between 7 m and 8 m.\n\n{{diagram:m8-estimate}}\n\n**Trap the root between two squares**\nBecause 49 < 50 < 64, we know 7 < √50 < 8. This is an estimate, not an exact answer. Write √50 ≈ 7.1 if using one decimal place, not √50 = 7.1.\n\n**Test a closer guess**\n7.0² = 49 and 7.1² = 50.41. So the root is between 7.0 and 7.1. Its nearest tenth is 7.1: the halfway value 7.05 has square 49.7025, below 50.\n\n**Why this matters**\nEstimation catches impossible answers. √200 cannot be 100: 14² = 196 and 15² = 225, so it must lie between 14 and 15.\n\n**A common mistake**\nBeing halfway between two square numbers does not make the root halfway between their roots. Squaring is not a straight-line relationship.\n\n**Try, discuss, apply**\nMove the garden area to 80. Find its neighbouring squares before reading the result. Would an 8 m side provide at least 80 m²? Explain why not.',
    '**क्या 7 m side काफी है?**\nSquare बगीचे में 50 m² जगह चाहिए। 7 m side से सिर्फ 49 m² मिलेगा। 8 m से 64 m² मिलेगा। सही side 7 m और 8 m के बीच है।\n\n{{diagram:m8-estimate}}\n\n**Root को दो squares के बीच रखिए**\n49 < 50 < 64 है, इसलिए 7 < √50 < 8। यह अंदाज़ा है, exact उत्तर नहीं। एक decimal तक √50 ≈ 7.1 लिखिए, √50 = 7.1 नहीं।\n\n**और पास जाकर जाँचिए**\n7.0² = 49 और 7.1² = 50.41। Root, 7.0 और 7.1 के बीच है। नज़दीकी tenth 7.1 है: बीच वाले 7.05 का square 49.7025 है, जो 50 से कम है।\n\n**यह क्यों काम का है?**\nअंदाज़े से गलत उत्तर पकड़ सकते हैं। √200, 100 नहीं हो सकता: 14² = 196 और 15² = 225, इसलिए root 14 और 15 के बीच होगा।\n\n**एक आम भूल**\nदो square numbers के ठीक बीच की संख्या का root, उनके roots के ठीक बीच होना ज़रूरी नहीं। Squaring बराबर गति से नहीं बढ़ती।\n\n**करिए, समझाइए, लगाइए**\nबगीचे का area 80 कीजिए। उत्तर पढ़ने से पहले पास वाले squares खोजिए। क्या 8 m side कम-से-कम 80 m² जगह देगी? क्यों नहीं?'),b(
    'Suppose the garden needs fifty square metres. Seven times seven is forty-nine: a little too small. Eight times eight is sixty-four: too large for an exact fit. So the exact side is between seven and eight metres.\n\nThis is already useful. If someone gives you twenty-five metres as the root, you can reject it immediately. Always estimate before doing a longer calculation.\n\nFor a closer check, square seven point one. You get fifty point four one. The root of fifty lies below that, but above seven. To round to the nearest tenth, check seven point zero five: its square is below fifty, so round up to seven point one.\n\nUse the approximately-equal sign for a rounded answer. A rounded measurement is useful, but it is not exact. Try area eighty and explain which two whole-number side lengths surround its root.',
    'मान लीजिए बगीचे में पचास square metre जगह चाहिए। सात गुणा सात, उनचास: थोड़ा कम। आठ गुणा आठ, चौंसठ: exact जगह से ज़्यादा। इसलिए सही side सात और आठ metre के बीच है।\n\nइतनी जानकारी भी काम की है। कोई root पच्चीस metre बता दे तो आप तुरंत गलती पकड़ लेंगे। लंबा हिसाब करने से पहले अंदाज़ा लगाइए।\n\nऔर पास जाने के लिए सात दशमलव एक का square कीजिए। पचास दशमलव चार एक मिलेगा। पचास का root इससे कम, लेकिन सात से ज़्यादा है। Nearest tenth के लिए सात दशमलव शून्य पाँच जाँचिए। उसका square पचास से कम है, इसलिए सात दशमलव एक तक round करेंगे।\n\nRounded उत्तर के लिए लगभग बराबर का चिन्ह लगाइए। वह काम का अंदाज़ा है, exact उत्तर नहीं। अब area अस्सी लीजिए और root के दोनों तरफ की whole numbers बताइए।'),
    b('Between which consecutive whole numbers does √90 lie?','√90 किन लगातार whole numbers के बीच है?'),
    [['9² = 81 and 10² = 100.','9² = 81 और 10² = 100।','Use the neighbouring perfect squares.','दोनों तरफ के पास वाले perfect squares लीजिए।'],['81 < 90 < 100, so 9 < √90 < 10.','81 < 90 < 100, इसलिए 9 < √90 < 10।','Squaring increases for non-negative numbers.','Non-negative numbers बढ़ने पर उनका square भी बढ़ता है।']],b('Between 9 and 10, not exactly 9 or 10.','9 और 10 के बीच, ठीक 9 या 10 नहीं।'));

  lesson(6,b('6. A larger root, one digit at a time','6. बड़ा root, एक digit करके'),b(
    '**A large square display**\nThere are 2025 dots in a square display. The side is between 40 and 50 because 40² = 1600 and 50² = 2500. Can we find it exactly?\n\n{{diagram:m8-division}}\n\n**Pair digits from the right**\nWrite 20 | 25. One pair of digits gives one digit of the root. The largest square not exceeding 20 is 4² = 16. Write 4, subtract 16 from 20, and bring down 25: the remainder becomes 425.\n\n**Find the next digit**\nDouble the root so far: 2 × 4 = 8. Find the largest digit d for which (80 + d) × d ≤ 425. Try d = 5: 85 × 5 = 425. The root is 45 and the remainder is 0. Check 45² = 2025.\n\n**Why 80?**\nThe first root digit means 40. Growing a 40-by-40 square by d adds two strips of area 40d and a corner of area d². Together: (80 + d)d.\n\n**Watch the place value**\nDo not use (8 + d)d. The 8 must shift one place to make 80. Do not choose a digit that makes the product too large.\n\n**Try and reflect**\nUse the step buttons for 1296. Predict each next digit. Explain how the final multiplication check protects you from a place-value error.',
    '**बड़ा square display**\nSquare display में 2025 बिंदु हैं। Side 40 और 50 के बीच है, क्योंकि 40² = 1600 और 50² = 2500। Exact उत्तर कैसे मिलेगा?\n\n{{diagram:m8-division}}\n\n**दाईं ओर से digits की जोड़ी बनाइए**\n20 | 25 लिखिए। हर digit-pair से root का एक digit मिलता है। 20 से बड़ा न होने वाला सबसे बड़ा square, 4² = 16 है। 4 लिखिए। 20 में से 16 घटाकर अगली जोड़ी 25 नीचे लाइए: अब 425 है।\n\n**अगला digit खोजिए**\nअब तक के root को दोगुना कीजिए: 2 × 4 = 8। सबसे बड़ा digit d खोजिए जिसके लिए (80 + d) × d ≤ 425 हो। d = 5 पर 85 × 5 = 425। Root 45 और remainder 0 है। जाँच: 45² = 2025।\n\n**80 क्यों आया?**\nपहला root digit यहाँ 40 बताता है। 40-by-40 square को d से बढ़ाने पर 40d की दो पट्टियाँ और d² का कोना जुड़ता है। कुल (80 + d)d।\n\n**Place value ध्यान से**\n(8 + d)d नहीं लेना है। 8 को एक स्थान आगे करके 80 बनाना है। ऐसा digit मत चुनिए जिससे product ज़्यादा हो जाए।\n\n**करके समझिए**\nStep buttons से 1296 हल कीजिए। हर अगला digit पहले सोचिए। आखिर में गुणा करके जाँचने से place-value की गलती कैसे पकड़ेंगे?'),b(
    'We want the square root of two thousand and twenty-five. First estimate: it lies between forty and fifty. Pair the digits from the right: twenty, then twenty-five.\n\nThe largest square that fits inside twenty is sixteen, which is four squared. Write four as the first root digit. Subtract sixteen, leaving four, and bring down the next pair to make four hundred and twenty-five.\n\nDouble the root digit four to get eight. Shift it one place to eighty. Try a new digit five: eighty-five times five is four hundred and twenty-five, exactly. Write five beside four. The answer is forty-five.\n\nWhy eighty? Two strips each have width forty, so together they contribute eighty times the new digit. The small corner contributes the digit squared. Finally, forty-five times forty-five equals two thousand and twenty-five. The estimate and exact check agree.',
    'हमें दो हज़ार पच्चीस का square root चाहिए। पहले अंदाज़ा: चालीस और पचास के बीच। दाईं ओर से digits की जोड़ी बनाइए: बीस, फिर पच्चीस।\n\nबीस से बड़ा न होने वाला सबसे बड़ा square सोलह है, यानी चार का square। Root का पहला digit चार लिखिए। सोलह घटाने पर चार बचा। अगली जोड़ी नीचे लाने पर चार सौ पच्चीस बनेगा।\n\nचार को दोगुना करके आठ मिला। एक स्थान आगे करके अस्सी लीजिए। नया digit पाँच आज़माइए। पचासी गुणा पाँच ठीक चार सौ पच्चीस है। चार के साथ पाँच लिखिए। उत्तर पैंतालीस।\n\nअस्सी क्यों? चालीस चौड़ाई की दो पट्टियाँ मिलकर नए digit का अस्सी गुना area जोड़ती हैं। छोटा कोना digit का square जोड़ता है। आखिर में पैंतालीस गुणा पैंतालीस करके दो हज़ार पच्चीस जाँचिए।'),
    b('Find √1296 by the digit-pair method.','Digit-pair तरीके से √1296 खोजिए।'),
    [['12 | 96: 3² = 9; remainder 3, bring down 96 → 396.','12 | 96: 3² = 9; शेष 3, 96 नीचे लाएँ → 396।','3 is the largest first digit that fits.','फिट होने वाला सबसे बड़ा पहला digit 3 है।'],['Double 3 → 6; (60 + 6) × 6 = 396.','3 का दोगुना 6; (60 + 6) × 6 = 396।','The next digit is 6 and the remainder is zero.','अगला digit 6 है और शेष शून्य है।']],b('√1296 = 36; 36 × 36 = 1296.','√1296 = 36; 36 × 36 = 1296।'));

  lesson(7,b('7. Cubes are square layers','7. Square परतों से cube'),b(
    '**From a floor to a stack**\nKabir stacks small identical cubes for a school model. A layer has 3 rows of 3 cubes. How many such layers make a big cube?\n\n{{diagram:m8-cube}}\n\n**Count all three directions**\nEach layer has 3 × 3 = 9 cubes. Three layers contain 9 × 3 = 27. We write 3³ = 3 × 3 × 3 = 27, read “three cubed”. A cube has equal length, width and height.\n\n**Square or cube?**\n3² counts a flat 3-by-3 array. 3³ counts a 3-by-3-by-3 stack. Neither means 3 × 2 or 3 × 3 just because of the small exponent.\n\n**Units tell the story**\nA cube of side 4 cm has volume 64 cm³. One cubic centimetre is the space in a 1 cm × 1 cm × 1 cm cube.\n\n**Predict before moving**\nChange the side from 2 to 4. The volume goes from 8 to 64: eight times as much! All three directions doubled.\n\n**Numbers can be negative too**\n(−2)³ = (−2)(−2)(−2) = −8. Unlike squaring, cubing keeps a negative sign. Physical lengths still cannot be negative.\n\n**Apply**\nSketch the layers of a 5-by-5-by-5 stack. Explain why seeing only the front face misses most of the cubes.',
    '**फर्श से ऊँचे ढेर तक**\nकबीर स्कूल model के लिए बराबर छोटे cubes जमा रहा है। एक परत में 3 की 3 पंक्तियाँ हैं। बड़ा cube बनाने के लिए ऐसी कितनी परतें चाहिए?\n\n{{diagram:m8-cube}}\n\n**तीनों दिशाओं में गिनिए**\nहर परत में 3 × 3 = 9 cubes हैं। तीन परतों में 9 × 3 = 27। इसे 3³ = 3 × 3 × 3 = 27 लिखते हैं और “तीन का घन” कहते हैं। Cube की लंबाई, चौड़ाई और ऊँचाई बराबर होती हैं।\n\n**Square या cube?**\n3² में सपाट 3-by-3 array गिनते हैं। 3³ में 3-by-3-by-3 ढेर गिनते हैं। छोटे exponent को देखकर सिर्फ 3 × 2 या 3 × 3 नहीं करना है।\n\n**Units भी समझाती हैं**\n4 cm side वाले cube का volume 64 cm³ है। एक cubic centimetre, 1 cm × 1 cm × 1 cm cube की जगह है।\n\n**बदलने से पहले सोचिए**\nSide 2 से 4 कीजिए। Volume 8 से 64 हो गया: आठ गुना! तीनों दिशाएँ दोगुनी हुई हैं।\n\n**Negative संख्या भी हो सकती है**\n(−2)³ = (−2)(−2)(−2) = −8। Square से अलग, cube में negative sign रहता है। असली लंबाई फिर भी negative नहीं हो सकती।\n\n**लगाकर देखिए**\n5-by-5-by-5 ढेर की परतें बनाइए। सिर्फ सामने का हिस्सा देखने से बहुत-से cubes क्यों छूट जाएँगे?'),b(
    'Kabir has made a layer with three rows of three small cubes. That is nine cubes, but the model is still only one layer high. To make a large cube, he needs three layers. Nine times three gives twenty-seven.\n\nThree cubed means three multiplied by three multiplied by three. We count length, width, and height. The cube of a whole number is called a perfect cube.\n\nMove the side from two to four. Predict the new volume first. It grows from eight to sixty-four, eight times as much. Doubling each of three directions multiplies the volume by two times two times two.\n\nA square counts area in square units. A cube measures volume in cubic units. And negative two cubed is negative eight, because the third negative factor changes the sign back to negative. That is number arithmetic, not a negative physical side length.',
    'कबीर ने तीन की तीन पंक्तियों वाली एक परत बनाई है। इसमें नौ छोटे cubes हैं। लेकिन model अभी सिर्फ एक परत ऊँचा है। बड़ा cube बनाने के लिए तीन परतें चाहिए। नौ गुणा तीन, सत्ताईस।\n\nतीन का cube मतलब तीन गुणा तीन गुणा तीन। लंबाई, चौड़ाई और ऊँचाई, तीनों गिननी हैं। Whole number के cube को perfect cube कहते हैं।\n\nSide दो से चार करने से पहले नए volume का अंदाज़ा लगाइए। आठ से चौंसठ हो गया, यानी आठ गुना। तीनों दिशाएँ दोगुनी होने से दो गुणा दो गुणा दो का असर पड़ा।\n\nSquare में area को square units में गिनते हैं। Cube का volume cubic units में है। ऋण दो का cube ऋण आठ है। तीसरा negative factor sign को फिर negative कर देता है। यह संख्याओं का हिसाब है, असली negative side नहीं।'),
    b('A cube has side 5 cm. Find its volume.','Cube की side 5 cm है। Volume खोजिए।'),
    [['One layer has 5 × 5 = 25 unit cubes.','एक परत में 5 × 5 = 25 unit cubes हैं।','First count the square base.','पहले square आधार गिनिए।'],['Five layers contain 25 × 5 = 125.','पाँच परतों में 25 × 5 = 125 हैं।','Include height as well as length and width.','लंबाई और चौड़ाई के साथ ऊँचाई भी लीजिए।']],b('125 cm³.','125 cm³।'));

  lesson(8,b('8. Cube roots: make groups of three','8. Cube root: तीन-तीन का समूह'),b(
    '**Rebuild the stack**\nA box contains 216 identical unit cubes. Kabir wants one solid cube with no gaps. How many cubes go along each edge?\n\n{{diagram:m8-triples}}\n\n**Undo three equal factors**\n6 × 6 × 6 = 216, so ∛216 = 6. The small 3 on the root sign tells us this is a cube root, not a square root. Do not divide 216 by 3.\n\n**Use prime triples**\n216 = (2 × 2 × 2)(3 × 3 × 3). Take one factor from each group of three: 2 × 3 = 6. Cubing 6 recreates all six prime factors.\n\n**Pairs are not enough**\n64 = 2 × 2 × 2 × 2 × 2 × 2. For a cube root, make two triples to get 2 × 2 = 4. For a square root, make three pairs to get 2 × 2 × 2 = 8. The same number can be both a square and a cube.\n\n**Try the sign**\n∛(−125) = −5 because (−5)³ = −125. Unlike √125, the cube root of a negative number is allowed in real-number arithmetic.\n\n**Reflect and apply**\nSelect 1000 in the lab and predict its edge length. Explain why a 1000 cm³ cube has side 10 cm, not 100 cm.',
    '**ढेर फिर बनाइए**\nडिब्बे में 216 बराबर unit cubes हैं। कबीर बिना खाली जगह वाला बड़ा cube बनाना चाहता है। हर किनारे पर कितने छोटे cubes होंगे?\n\n{{diagram:m8-triples}}\n\n**तीन बराबर factors को उल्टा कीजिए**\n6 × 6 × 6 = 216, इसलिए ∛216 = 6। Root के पास छोटा 3 बताता है कि यह cube root है, square root नहीं। 216 को 3 से भाग नहीं देना है।\n\n**Prime triples बनाइए**\n216 = (2 × 2 × 2)(3 × 3 × 3)। हर तीन के समूह से एक factor लीजिए: 2 × 3 = 6। 6 का cube करने पर सभी छह prime factors वापस आ जाते हैं।\n\n**सिर्फ जोड़ी काफी नहीं**\n64 = 2 × 2 × 2 × 2 × 2 × 2। Cube root के लिए दो triples बनेंगे: 2 × 2 = 4। Square root के लिए तीन जोड़ियाँ बनेंगी: 2 × 2 × 2 = 8। एक ही संख्या square और cube दोनों हो सकती है।\n\n**Sign भी जाँचिए**\n∛(−125) = −5 क्योंकि (−5)³ = −125। Negative संख्या का cube root real-number हिसाब में संभव है।\n\n**समझाइए और लगाइए**\nLab में 1000 चुनकर edge length पहले सोचिए। 1000 cm³ वाले cube की side 10 cm क्यों है, 100 cm क्यों नहीं?'),b(
    'We have two hundred and sixteen small cubes. A cube root asks for the number along each of three equal edges. Six times six times six equals two hundred and sixteen, so the edge is six.\n\nFor a systematic method, split two hundred and sixteen into prime factors. There are three twos and three threes. Make a triple of twos and a triple of threes. Pick one from each triple and multiply: two times three equals six.\n\nDo not use pairs for a cube root. For sixty-four, six twos form two triples, giving four. The same six twos form three pairs for a square root, giving eight. The root symbol tells you which grouping to use.\n\nA negative number has a negative cube root. Negative five times negative five times negative five is negative one hundred and twenty-five. Check your answer by cubing it, not by multiplying it by three.',
    'हमारे पास दो सौ सोलह छोटे cubes हैं। Cube root पूछता है: तीन बराबर किनारों में हर किनारे पर कितने होंगे? छह गुणा छह गुणा छह, दो सौ सोलह है। इसलिए किनारा छह है।\n\nतरीका लगाकर खोजने के लिए prime factors बनाइए। तीन बार दो और तीन बार तीन मिलेंगे। दो का एक triple और तीन का एक triple बनाइए। हर triple से एक लेकर गुणा कीजिए: दो गुणा तीन, छह।\n\nCube root में जोड़ियाँ मत बनाइए। चौंसठ के छह twos से दो triples बनते हैं, तो उत्तर चार है। उन्हीं छह twos की तीन जोड़ियाँ बनेंगी तो square root आठ मिलेगा। Root का चिन्ह देखकर समूह चुनिए।\n\nNegative संख्या का cube root negative होता है। ऋण पाँच गुणा ऋण पाँच गुणा ऋण पाँच, ऋण एक सौ पच्चीस है। अपने उत्तर का cube करके जाँचिए, सिर्फ तीन से गुणा करके नहीं।'),
    b('Find ∛1728 using prime triples.','Prime triples से ∛1728 खोजिए।'),
    [['1728 = (2 × 2 × 2)(2 × 2 × 2)(3 × 3 × 3).','1728 = (2 × 2 × 2)(2 × 2 × 2)(3 × 3 × 3)।','All factors fit complete triples.','सभी factors पूरे triples में हैं।'],['2 × 2 × 3 = 12.','2 × 2 × 3 = 12।','Select one prime from each triple.','हर triple से एक prime लीजिए।']],b('12; 12³ = 1728.','12; 12³ = 1728।'));

  lesson(9,b('9. Complete an unfinished cube','9. अधूरे cube को पूरा कीजिए'),b(
    '**The factor detective**\nKabir has 72 unit cubes. They do not form a solid cube. What is the smallest positive whole-number multiplier that makes the count a perfect cube?\n\n{{diagram:m8-complete}}\n\n**Count what each triple needs**\n72 = 2³ × 3². The twos already make a triple. The two threes need one more 3. Multiply by 3: 72 × 3 = 216 = 6³. No extra 2 is needed.\n\n**Division asks a different question**\nTo make a cube by division, remove the incomplete group of two threes. Divide by 9: 72 ÷ 9 = 8 = 2³. Dividing by 3 alone leaves 24, not a cube.\n\n**Multiplier is not “how many to add”**\nMultiplying 72 by 3 gives 216. If asked how many cubes to add to reach 216, the answer is 216 − 72 = 144. Different operations, different answers!\n\n**Try another case**\nFor 108 = 2² × 3³, multiply by 2 to complete a cube; divide by 4 to remove the incomplete group. Explain why these answers differ.\n\n**Remember**\nFor a perfect square, prime counts come in twos. For a perfect cube, they come in threes. A number that is both needs counts divisible by 6. That is why 64 = 2⁶ is both.\n\n**Apply**\nInvent a number with exactly one incomplete triple. Ask a friend to find its missing factor.',
    '**Factors के जासूस बनिए**\nकबीर के पास 72 unit cubes हैं। उनसे ठोस cube नहीं बनता। किस सबसे छोटी धनात्मक whole number से गुणा करने पर गिनती perfect cube होगी?\n\n{{diagram:m8-complete}}\n\n**हर triple की कमी गिनिए**\n72 = 2³ × 3²। Twos का triple पूरा है। दो threes को एक और 3 चाहिए। 3 से गुणा कीजिए: 72 × 3 = 216 = 6³। कोई नया 2 नहीं चाहिए।\n\n**भाग देने का सवाल अलग है**\nभाग देकर cube बनाने के लिए दो threes का अधूरा समूह हटाइए। 9 से भाग देने पर 72 ÷ 9 = 8 = 2³। सिर्फ 3 से भाग देने पर 24 बचेगा, जो cube नहीं है।\n\n**Multiplier और “कितने जोड़ें” अलग हैं**\n72 को 3 से गुणा करने पर 216 है। लेकिन 216 तक पहुँचने के लिए कितने cubes जोड़ें? उत्तर 216 − 72 = 144। क्रिया अलग, उत्तर अलग!\n\n**एक और मामला**\n108 = 2² × 3³ में 2 से गुणा करके cube पूरा होगा। 4 से भाग देकर अधूरा समूह हटेगा। दोनों उत्तर अलग क्यों हैं?\n\n**याद रखिए**\nPerfect square में prime की गिनती दो-दो में और perfect cube में तीन-तीन में होती है। दोनों होने के लिए गिनती 6 से divisible होनी चाहिए। इसलिए 64 = 2⁶ दोनों है।\n\n**ख़ुद बनाइए**\nऐसी संख्या बनाइए जिसमें सिर्फ एक triple अधूरा हो। साथी से उसका missing factor पूछिए।'),b(
    'Seventy-two does not make a perfect cube. Its prime factors are three twos and two threes. The twos are complete. The threes need only one more partner to make a group of three. So multiply by three.\n\nThe new count is two hundred and sixteen, which is six cubed. We did not need to multiply by every prime again, only the missing one.\n\nNow ask a different question: what is the smallest number to divide by? Remove both ungrouped threes, so divide by nine. Eight remains, which is two cubed. Dividing by three leaves twenty-four, and that still is not a cube.\n\nOne last distinction: multiplying by three is not adding three blocks. To grow seventy-two to two hundred and sixteen by addition, you need one hundred and forty-four more blocks. Read the operation carefully before choosing your answer.',
    'बहत्तर perfect cube नहीं है। उसके prime factors में तीन बार दो और दो बार तीन हैं। Twos का समूह पूरा है। Threes का triple बनाने के लिए सिर्फ एक और तीन चाहिए। इसलिए तीन से गुणा कीजिए।\n\nनई गिनती दो सौ सोलह है, यानी छह का cube। हर prime को फिर से गुणा नहीं करना है। सिर्फ कमी पूरी करनी है।\n\nअब अलग सवाल पूछिए: सबसे छोटी किस संख्या से भाग दें? अधूरे समूह के दोनों threes हटाइए, यानी नौ से भाग दीजिए। आठ बचेगा, जो दो का cube है। सिर्फ तीन से भाग देने पर चौबीस बचता है, जो cube नहीं है।\n\nएक आखिरी अंतर: तीन से गुणा करना और तीन blocks जोड़ना अलग बातें हैं। बहत्तर से दो सौ सोलह तक जोड़कर पहुँचने के लिए एक सौ चवालीस नए blocks चाहिए। उत्तर चुनने से पहले क्रिया ध्यान से पढ़िए।'),
    b('Find the smallest multiplier making 200 a perfect cube.','200 को perfect cube बनाने वाला सबसे छोटा धनात्मक whole-number multiplier खोजिए।'),
    [['200 = 2³ × 5².','200 = 2³ × 5²।','The twos are complete; one five is missing.','Twos पूरे हैं; एक five कम है।'],['200 × 5 = 1000 = 10³.','200 × 5 = 1000 = 10³।','Only complete the unfinished triple.','सिर्फ अधूरा triple पूरा कीजिए।']],b('Multiply by 5, not by 10.','5 से गुणा कीजिए, 10 से नहीं।'));

  lesson(10,b('10. Plan a garden and a model box','10. बगीचे और model box की योजना'),b(
    '**Two jobs, two different roots**\nThe school wants a square garden of area 144 m² and a cube-shaped model box of volume 125 cm³. Rani says, “Use square root for both.” Would you agree? Discuss before calculating.\n\n{{diagram:m8-plan}}\n\n**Choose by the shape**\nThe garden has two equal directions: side = √144 = 12 m. Fencing goes around its edge, so fence length = 4 × 12 = 48 m.\n\nThe box has three equal directions: edge = ∛125 = 5 cm. Do not take √125. Its volume was made by multiplying three equal lengths.\n\n**Read the units**\nm² tells you area; cm³ tells you volume. Keep the units from each problem separate. We are not claiming the model box can hold the garden!\n\n**Budget with a condition**\nIf the garden fence costs ₹30 per metre, 48 m costs ₹1440. This assumes a complete boundary, no gate, no wastage and no labour charges. State assumptions rather than hiding them.\n\n**Check, then communicate**\n12 × 12 gives the required 144. And 5 × 5 × 5 gives the required 125. Explain the method, not only the final number.\n\n**Your practical task**\nDraw a square design on paper and build or sketch a cube in layers. Label side, area, perimeter and volume correctly. Use the chapter’s Practical Activity for a complete task and answer guide.',
    '**दो काम, दो अलग roots**\nस्कूल को 144 m² का square बगीचा और 125 cm³ का cube-shaped model box चाहिए। रानी कहती है, “दोनों में square root लेंगे।” क्या आप मानेंगे? हिसाब से पहले चर्चा कीजिए।\n\n{{diagram:m8-plan}}\n\n**Shape देखकर चुनिए**\nबगीचे की दो दिशाएँ बराबर हैं: side = √144 = 12 m। बाड़ उसके किनारे पर लगेगी, इसलिए लंबाई 4 × 12 = 48 m।\n\nBox की तीन दिशाएँ बराबर हैं: edge = ∛125 = 5 cm। √125 मत लीजिए। Volume तीन बराबर लंबाइयाँ गुणा करके बना था।\n\n**Units पढ़िए**\nm² area और cm³ volume बताता है। दोनों सवालों की units अलग रखिए। Model box में बगीचा रखने की बात नहीं हो रही है!\n\n**शर्त के साथ खर्च**\nबाड़ ₹30 प्रति metre हो तो 48 m का खर्च ₹1440 होगा। यहाँ पूरा किनारा बंद है, gate नहीं है, wastage और मजदूरी शामिल नहीं हैं। शर्तें साफ बताइए।\n\n**जाँचकर समझाइए**\n12 × 12 से चाहिए वाला 144 मिलता है। 5 × 5 × 5 से 125 मिलता है। सिर्फ उत्तर नहीं, तरीका भी बताइए।\n\n**आपका practical काम**\nकागज़ पर square design बनाइए। Cube को परतों में बनाइए या उसका चित्र बनाइए। Side, area, perimeter और volume सही लिखिए। पूरे काम और answer guide के लिए chapter की Practical Activity खोलिए।'),b(
    'We now have two real planning jobs. A square garden has area one hundred and forty-four square metres. A small cube-shaped model box has volume one hundred and twenty-five cubic centimetres. Which root belongs to each?\n\nThe garden has two equal side directions, so use a square root. Its side is twelve metres. The fence goes around four sides, so we need forty-eight metres of fencing.\n\nThe box has three equal edge directions, so use a cube root. Five times five times five is one hundred and twenty-five. Its edge is five centimetres.\n\nAt thirty rupees per metre, the garden fence costs one thousand four hundred and forty rupees. Say what this assumes: no gate, no waste, and no labour cost. A good mathematical answer includes a method, units, a check, and any assumptions. Now change the plan and explain it to someone without reading the notes.',
    'अब दो असली planning वाले काम हैं। Square बगीचे का area एक सौ चवालीस square metre है। छोटे cube-shaped model box का volume एक सौ पच्चीस cubic centimetre है। किसमें कौन-सा root लगेगा?\n\nबगीचे की दो side दिशाएँ बराबर हैं, इसलिए square root लीजिए। Side बारह metre है। चारों तरफ बाड़ के लिए अड़तालीस metre चाहिए।\n\nBox की तीन दिशाएँ बराबर हैं, इसलिए cube root लीजिए। पाँच गुणा पाँच गुणा पाँच, एक सौ पच्चीस है। उसका किनारा पाँच centimetre है।\n\nतीस रुपये प्रति metre पर बगीचे की बाड़ का खर्च एक हज़ार चार सौ चालीस रुपये है। शर्तें भी बताइए: gate नहीं है, wastage नहीं है और मजदूरी नहीं जोड़ी है। अच्छे उत्तर में तरीका, units, जाँच और शर्तें होती हैं। अब plan बदलकर बिना notes पढ़े किसी को समझाइए।'),
    b('A square garden has area 81 m². Fence costs ₹20/m, with no gate or extra charges. Find the cost.','Square बगीचे का area 81 m² है। बिना gate या अतिरिक्त खर्च के बाड़ ₹20/m है। कुल खर्च खोजिए।'),
    [['Side = √81 = 9 m.','Side = √81 = 9 m।','Find a length from the square area.','Square area से लंबाई खोजिए।'],['Perimeter = 4 × 9 = 36 m.','Perimeter = 4 × 9 = 36 m।','Fence runs along the four sides.','बाड़ चारों sides पर लगती है।'],['Cost = 36 × 20 = ₹720.','खर्च = 36 × 20 = ₹720।','Multiply length by cost per metre.','लंबाई को प्रति metre खर्च से गुणा कीजिए।']],b('₹720, under the stated assumptions.','दी गई शर्तों के अनुसार ₹720।'));

  var qs=[];
  function q(n,type,en,hi,correct,exen,exhi,extra){
    var item={id:'M8-Q'+String(qs.length+1).padStart(3,'0'),board:'JAC/CBSE',klass:8,subject:'MATH8',chapter:1,topic:'M8-1-'+n,type:type,diff:type==='subjective'?'hard':(type==='mcq'||type==='fill'?'easy':'medium'),status:'published',q:b(en,hi),correct:correct,exp:b(exen,exhi),source:'SelfLearn original Class 8 pilot',tags:['class8-pilot']};
    Object.assign(item,extra||{}); qs.push(item); return item;
  }
  function mc(n,en,hi,opts,ans,ee,eh){q(n,'mcq',en,hi,ans,ee,eh,{opts:b(opts.map(function(o){return o[0];}),opts.map(function(o){return o[1];}))});}
  function multi(n,en,hi,opts,ans,ee,eh){q(n,'multi',en,hi,ans,ee,eh,{opts:b(opts.map(function(o){return o[0];}),opts.map(function(o){return o[1];}))});}
  function fill(n,en,hi,ans,ee,eh){q(n,'fill',en,hi,String(ans),ee,eh);}
  function match(n,pairs,ee,eh){q(n,'match','Match each item with its partner.','हर चीज़ को उसके सही साथी से मिलाइए।','pairs',ee,eh,{pairs:pairs.map(function(p){return {l:b(p[0],p[1]),r:b(p[2],p[3])};})});}
  function written(n,en,hi,modelEn,modelHi,criteria){q(n,'subjective',en,hi,'self-review',modelEn,modelHi,{model:b(modelEn,modelHi),rubric:criteria.map(function(c){return b(c[0],c[1]);})});}
  function o(s){return [s,s];}
  mc(1,'6² means…','6² का मतलब है…',[o('6 × 6'),o('6 × 2'),o('6 + 6'),o('6 × 6 × 6')],'A','The exponent 2 means two equal factors: 6 × 6 = 36.','Exponent 2 का मतलब दो बराबर factors: 6 × 6 = 36।');
  mc(1,'A square has side 9 m. What is its area?','Square की side 9 m है। Area क्या है?',[o('18 m²'),o('36 m²'),o('81 m²'),o('729 m²')],'C','Area = side × side = 9 × 9 = 81 m². 36 m is its perimeter.','Area = side × side = 9 × 9 = 81 m²। उसका perimeter 36 m है।');
  mc(1,'Which tile layout is a square?','कौन-सी टाइल व्यवस्था square है?',[o('3 × 5'),o('4 × 4'),o('2 × 8'),o('1 × 6')],'B','Only 4 × 4 has equal counts along both sides.','सिर्फ 4 × 4 में दोनों sides पर बराबर गिनती है।');
  multi(1,'Choose ALL perfect squares.','सभी perfect squares चुनिए।',[o('0'),o('16'),o('20'),o('25')],['A','B','D'],'0² = 0, 4² = 16 and 5² = 25. 20 lies between 16 and 25.','0² = 0, 4² = 16 और 5² = 25। 20, 16 और 25 के बीच है।');
  fill(1,'A square array has 7 rows of 7 dots. Total dots = ___.','Square array में 7 बिंदुओं की 7 पंक्तियाँ हैं। कुल बिंदु = ___।',49,'7 × 7 = 49.','7 × 7 = 49।');
  fill(1,'A square has side 6 cm. Its perimeter is ___ cm.','Square की side 6 cm है। Perimeter ___ cm है।',24,'Four sides: 4 × 6 = 24 cm. Area would be 36 cm².','चार sides: 4 × 6 = 24 cm। Area 36 cm² होता।');
  match(1,[['2²','2²','4','4'],['3²','3²','9','9'],['5²','5²','25','25']],'Multiply each base by itself.','हर base को उसी से गुणा कीजिए।');
  written(1,'A friend says 8² = 16. Explain the mistake using rows of tiles.','साथी कहता है 8² = 16। टाइलों की पंक्तियों से गलती समझाइए।','8² means 8 rows with 8 tiles each, so 8 × 8 = 64. 16 is 8 × 2, which doubles 8 instead of squaring it.','8² में 8 टाइलों की 8 पंक्तियाँ हैं: 8 × 8 = 64। 16 तो 8 × 2 है, जो 8 को दोगुना करता है, square नहीं।',[['Show 8 equal rows of 8.','8 की 8 बराबर पंक्तियाँ दिखाईं।'],['Distinguish doubling from squaring.','दोगुना करने और square का अंतर बताया।'],['Give 64 with a multiplication check.','64 बताया और गुणा से जाँचा।']]);
  mc(2,'How many new tiles grow 5 × 5 into 6 × 6?','5 × 5 को 6 × 6 बनाने में कितनी नई टाइलें चाहिए?',[o('1'),o('10'),o('11'),o('36')],'C','36 − 25 = 11, or 5 + 5 + 1 = 11.','36 − 25 = 11, या 5 + 5 + 1 = 11।');
  mc(2,'Which ending rules out a whole-number square?','कौन-सा आखिरी digit whole-number square को असंभव बनाता है?',[o('1'),o('4'),o('8'),o('9')],'C','No whole-number square ends in 8.','किसी whole-number square का आखिरी digit 8 नहीं होता।');
  mc(2,'A number ends in 6. What can we conclude?','किसी संख्या का अंत 6 है। क्या कह सकते हैं?', [['Definitely a square','पक्का square'],['Definitely not a square','पक्का square नहीं'],['It might be a square; check further','Square हो सकता है; और जाँचें'],['Definitely odd','पक्का odd']],'C','16 is a square, but 26 is not. The ending alone is not proof.','16 square है, 26 नहीं। Ending अकेले प्रमाण नहीं है।');
  multi(2,'Choose ALL true statements.','सभी सही बातें चुनिए।',[['1 + 3 + 5 = 3²','1 + 3 + 5 = 3²'],['Every odd number is a square','हर odd संख्या square है'],['An even number has an even square','Even संख्या का square even है'],['A square can end in 3','Square का अंत 3 हो सकता है']],['A','C'],'1 + 3 + 5 = 9. Even × even is even. 3 is odd but not a square, and no square ends in 3.','1 + 3 + 5 = 9। Even × even, even है। 3 odd है पर square नहीं; square का अंत 3 नहीं होता।');
  fill(2,'The first 6 positive odd numbers add to ___.','पहली 6 धनात्मक odd संख्याओं का जोड़ ___ है।',36,'1 + 3 + 5 + 7 + 9 + 11 = 6² = 36.','1 + 3 + 5 + 7 + 9 + 11 = 6² = 36।');
  fill(2,'How many whole numbers lie strictly between 8² and 9²?','8² और 9² के ठीक बीच कितनी whole numbers हैं?',16,'81 − 64 − 1 = 16: the numbers 65 through 80.','81 − 64 − 1 = 16: 65 से 80 तक।');
  match(2,[['1² → 2²','1² → 2²','Add 3','3 जोड़ें'],['2² → 3²','2² → 3²','Add 5','5 जोड़ें'],['3² → 4²','3² → 4²','Add 7','7 जोड़ें']],'Successive square borders grow by odd numbers.','लगातार square के किनारे odd संख्याओं से बढ़ते हैं।');
  written(2,'Explain why an allowed last digit does not prove that 46 is a perfect square.','समझाइए कि आखिरी digit सही होने पर भी 46 perfect square क्यों नहीं है।','46 ends in 6, an allowed digit. But 6² = 36 and 7² = 49, and 46 lies strictly between them. No whole-number side gives 46.','46 का अंत 6 है, जो संभव digit है। लेकिन 6² = 36 और 7² = 49 के बीच 46 है। किसी whole-number side का square 46 नहीं है।',[['Recognise that 6 is an allowed ending.','6 को संभव ending बताया।'],['Use 36 and 49 as neighbouring squares.','36 और 49 वाले पड़ोसी squares लिए।'],['Explain why a clue is not proof.','संकेत प्रमाण क्यों नहीं है, समझाया।']]);
  mc(3,'√81 equals…','√81 बराबर है…',[o('9'),o('−9'),o('±9'),o('40.5')],'A','The root sign denotes the non-negative root: 9.','Root का चिन्ह non-negative root बताता है: 9।');
  mc(3,'A square has area 100 cm². Its side is…','Square का area 100 cm² है। Side है…',[o('50 cm'),o('10 cm'),o('25 cm'),o('100 cm')],'B','10 × 10 = 100, so the side is 10 cm.','10 × 10 = 100, इसलिए side 10 cm है।');
  mc(3,'√0.36 equals…','√0.36 बराबर है…',[o('0.06'),o('0.18'),o('0.6'),o('6')],'C','0.6 × 0.6 = 0.36.','0.6 × 0.6 = 0.36।');
  multi(3,'Which numbers solve x² = 25? Select ALL.','x² = 25 को हल करने वाली सभी संख्याएँ चुनिए।',[o('5'),o('−5'),o('12.5'),o('25')],['A','B'],'Both 5 × 5 and (−5) × (−5) equal 25. This equation differs from √25.','5 × 5 और (−5) × (−5), दोनों 25 हैं। यह equation, √25 से अलग है।');
  fill(3,'√121 = ___.','√121 = ___।',11,'11 × 11 = 121.','11 × 11 = 121।');
  fill(3,'√(9/16) = ___ (fraction or decimal).','√(9/16) = ___ (fraction या decimal)।','3/4|0.75','(3/4)² = 9/16, so the non-negative root is 3/4.','(3/4)² = 9/16, इसलिए non-negative root 3/4 है।');
  match(3,[['√16','√16','4','4'],['√0.04','√0.04','0.2','0.2'],['√1','√1','1','1']],'Square each answer to recover the number under the root.','हर उत्तर का square करके root के अंदर वाली संख्या जाँचिए।');
  written(3,'Is √64 = ±8? Explain the root sign and compare with x² = 64.','क्या √64 = ±8 है? Root के चिन्ह को समझाकर x² = 64 से तुलना कीजिए।','No. √64 = 8 because √ denotes the non-negative root. The equation x² = 64 has solutions 8 and −8 since both square to 64.','नहीं। √64 = 8, क्योंकि √ non-negative root है। x² = 64 के हल 8 और −8 हैं, क्योंकि दोनों का square 64 है।',[['State √64 = 8.','√64 = 8 लिखा।'],['Give both solutions of the equation.','Equation के दोनों हल दिए।'],['Explain the notation, not just the signs.','सिर्फ signs नहीं, चिन्ह का मतलब बताया।']]);
  mc(4,'√324 equals…','√324 बराबर है…',[o('16'),o('18'),o('162'),o('36')],'B','324 = 2² × 3⁴; take one from each pair: 2 × 3 × 3 = 18.','324 = 2² × 3⁴; हर जोड़ी से एक लीजिए: 2 × 3 × 3 = 18।');
  mc(4,'Smallest positive whole-number multiplier making 72 a square?','72 को square बनाने वाला सबसे छोटा धनात्मक whole-number multiplier?', [o('2'),o('3'),o('6'),o('8')],'A','72 = 2³ × 3². One extra 2 completes all pairs.','72 = 2³ × 3²। एक और 2 सभी जोड़ियाँ पूरी करता है।');
  mc(4,'Which prime counts describe a perfect square?','कौन-सी prime गिनती perfect square बनाती है?',[o('2³ × 3²'),o('2² × 3⁴'),o('2 × 3'),o('5³')],'B','All prime exponents must be even. Only 2² × 3⁴ meets that condition.','सभी prime exponents even होने चाहिए। सिर्फ 2² × 3⁴ में ऐसा है।');
  multi(4,'Which operations make 180 a perfect square? Choose ALL.','कौन-सी क्रियाएँ 180 को perfect square बनाती हैं? सभी चुनिए।',[o('180 × 5'),o('180 ÷ 5'),o('180 × 2'),o('180 ÷ 3')],['A','B'],'180 = 2² × 3² × 5. Multiplying by 5 gives 900; dividing by 5 gives 36. 360 and 60 are not squares.','180 = 2² × 3² × 5। 5 से गुणा पर 900, भाग पर 36। 360 और 60 square नहीं हैं।');
  fill(4,'√400 = ___.','√400 = ___।',20,'400 = 2⁴ × 5²; the root is 2² × 5 = 20.','400 = 2⁴ × 5²; root 2² × 5 = 20 है।');
  fill(4,'Smallest positive whole number to divide 98 by to get a perfect square = ___.','98 को perfect square बनाने के लिए सबसे छोटी किस धनात्मक whole number से भाग दें? ___।',2,'98 = 2 × 7². Remove the unpaired 2 to get 49.','98 = 2 × 7²। अकेला 2 हटाने पर 49 मिलता है।');
  match(4,[['√36','√36','2 × 3','2 × 3'],['√225','√225','3 × 5','3 × 5'],['√196','√196','2 × 7','2 × 7']],'Each expression takes one prime from each pair.','हर expression में हर prime जोड़ी से एक लिया है।');
  written(4,'Show why 48 is not a square. Find the smallest positive multiplier that makes it one.','48 square क्यों नहीं है? उसे square बनाने वाला सबसे छोटा धनात्मक whole-number multiplier खोजिए।','48 = 2⁴ × 3. The 3 is unpaired. Multiply by 3 to get 144 = 12². The pairs of twos need no extra factor.','48 = 2⁴ × 3। 3 अकेला है। 3 से गुणा करने पर 144 = 12²। Twos की जोड़ियों में कोई कमी नहीं।',[['Give the prime factorisation.','Prime factorisation दिया।'],['Identify the lonely 3.','अकेला 3 पहचाना।'],['Verify 48 × 3 = 12² and minimality.','48 × 3 = 12² और सबसे छोटा multiplier समझाया।']]);
  mc(5,'√70 lies between…','√70 इनके बीच है…',[o('6 and 7'),o('7 and 8'),o('8 and 9'),o('9 and 10')],'C','8² = 64 < 70 < 81 = 9².','8² = 64 < 70 < 81 = 9²।');
  mc(5,'Which is a correct approximate statement?','कौन-सा लगभग वाला कथन सही है?',[o('√50 = 7'),o('√50 ≈ 7.1'),o('√50 = 25'),o('√50 ≈ 50')],'B','7.1 is the root rounded to one decimal place, not an exact equality.','7.1 एक decimal तक rounded root है, exact बराबरी नहीं।');
  mc(5,'The least whole-number side giving at least 80 m² of square area is…','कम-से-कम 80 m² square area के लिए सबसे छोटी whole-number side है…',[o('8 m'),o('9 m'),o('10 m'),o('40 m')],'B','8² = 64 is too small; 9² = 81 is enough.','8² = 64 कम है; 9² = 81 काफी है।');
  multi(5,'Choose ALL true bounds.','सभी सही सीमाएँ चुनिए।',[o('7 < √60 < 8'),o('10 < √120 < 11'),o('5 < √40 < 6'),o('14 < √200 < 15')],['A','B','D'],'49 < 60 < 64; 100 < 120 < 121; 196 < 200 < 225. √40 lies between 6 and 7, not 5 and 6.','49 < 60 < 64; 100 < 120 < 121; 196 < 200 < 225। √40, 6 और 7 के बीच है।');
  fill(5,'The greatest whole number less than √30 is ___.','√30 से छोटी सबसे बड़ी whole number ___ है।',5,'25 < 30 < 36, so 5 < √30 < 6.','25 < 30 < 36, इसलिए 5 < √30 < 6।');
  fill(5,'√150 lies between 12 and ___ (the next whole number).','√150, 12 और अगली whole number ___ के बीच है।',13,'12² = 144 and 13² = 169.','12² = 144 और 13² = 169।');
  match(5,[['√20','√20','Between 4 and 5','4 और 5 के बीच'],['√55','√55','Between 7 and 8','7 और 8 के बीच'],['√110','√110','Between 10 and 11','10 और 11 के बीच']],'Bracket each number using neighbouring squares.','हर संख्या को पास वाले squares के बीच रखिए।');
  written(5,'A friend claims √130 = 65. Reject the answer without finding the exact root.','साथी कहता है √130 = 65। Exact root निकाले बिना इसे गलत साबित कीजिए।','11² = 121 and 12² = 144. Since 121 < 130 < 144, its root is between 11 and 12. It cannot be 65. Dividing by 2 does not undo squaring.','11² = 121 और 12² = 144। 121 < 130 < 144, इसलिए root 11 और 12 के बीच है, 65 नहीं। 2 से भाग देना squaring की उल्टी क्रिया नहीं है।',[['Use 121 and 144.','121 और 144 का उपयोग किया।'],['Conclude 11 < √130 < 12.','11 < √130 < 12 बताया।'],['Explain the divide-by-two error.','2 से भाग देने की गलती समझाई।']]);
  mc(6,'How should 2025 be grouped for the square-root method?','Square-root तरीके में 2025 की grouping कैसे होगी?',[o('2 | 025'),o('20 | 25'),o('202 | 5'),o('2 | 0 | 2 | 5')],'B','Group digits in pairs starting from the right.','दाईं ओर से दो-दो digits का समूह बनाइए।');
  mc(6,'For 20 | 25, the first root digit is…','20 | 25 के लिए पहला root digit है…',[o('2'),o('3'),o('4'),o('5')],'C','4² = 16 fits within 20, while 5² = 25 is too large.','4² = 16, 20 से कम है; 5² = 25 ज़्यादा है।');
  mc(6,'After root digit 4, which expression tests digit 5?','Root digit 4 के बाद digit 5 जाँचने के लिए कौन-सा expression है?',[o('(8 + 5) × 5'),o('(80 + 5) × 5'),o('80 + 5'),o('4 × 5')],'B','Double 4 to get 8, shift to 80, append 5 and multiply by 5.','4 का दोगुना 8, फिर 80 बनाइए; 5 लगाकर 5 से गुणा कीजिए।');
  multi(6,'Choose ALL correct checks.','सभी सही जाँच चुनिए।',[o('36² = 1296'),o('45² = 2025'),o('35² = 1296'),o('50² = 2500')],['A','B','D'],'36² = 1296, 45² = 2025, 50² = 2500. But 35² = 1225.','36² = 1296, 45² = 2025, 50² = 2500। लेकिन 35² = 1225।');
  fill(6,'√2304 = ___.','√2304 = ___।',48,'23 | 04: 4² = 16; bring down to get 704. (80 + 8) × 8 = 704.','23 | 04: 4² = 16; नीचे लाने पर 704। (80 + 8) × 8 = 704।');
  fill(6,'In √1296, after subtracting 9 from 12 and bringing down 96, the working number is ___.','√1296 में 12 से 9 घटाकर 96 नीचे लाने पर संख्या ___ बनती है।',396,'The remainder 3 shifts two places, then 96 is appended: 396.','शेष 3 दो स्थान आगे जाता है, फिर 96 लगता है: 396।');
  match(6,[['√1024','√1024','32','32'],['√1225','√1225','35','35'],['√1600','√1600','40','40']],'Check each result by squaring: 32², 35² and 40².','हर उत्तर को square करके जाँचिए: 32², 35² और 40²।');
  written(6,'Find √2025 by digit pairs. Explain why the trial divisor starts with 80, not 8.','Digit pairs से √2025 खोजिए। Trial divisor में 8 की जगह 80 क्यों आता है?','20 | 25. Use 4² = 16; remainder 4, bring down 25 to make 425. Double 4 to get 8 and shift one place. (80 + 5) × 5 = 425, so √2025 = 45. The first digit represents 40; two added strips contribute 80d.','20 | 25। 4² = 16; शेष 4, 25 नीचे लाने पर 425। 4 को दोगुना कर 8, फिर एक स्थान आगे। (80 + 5) × 5 = 425, इसलिए √2025 = 45। पहला digit 40 है; दो नई पट्टियों का area 80d है।',[['Pair and bring down correctly.','जोड़ी और bring-down सही किया।'],['Use (80 + 5) × 5.','(80 + 5) × 5 लिया।'],['Explain place value and check 45².','Place value समझाई और 45² जाँचा।']]);
  mc(7,'4³ equals…','4³ बराबर है…',[o('12'),o('16'),o('64'),o('256')],'C','4 × 4 × 4 = 64.','4 × 4 × 4 = 64।');
  mc(7,'A cube has side 2 cm. Its volume is…','Cube की side 2 cm है। Volume है…',[o('4 cm²'),o('6 cm³'),o('8 cm³'),o('8 cm')],'C','2 × 2 × 2 = 8 cubic centimetres.','2 × 2 × 2 = 8 cubic centimetre।');
  mc(7,'(−3)³ equals…','(−3)³ बराबर है…',[o('27'),o('−27'),o('−9'),o('9')],'B','(−3)(−3) = 9, then 9 × (−3) = −27.','(−3)(−3) = 9, फिर 9 × (−3) = −27।');
  multi(7,'Choose ALL true statements about a 3 × 3 × 3 stack.','3 × 3 × 3 ढेर के बारे में सभी सही बातें चुनिए।',[['Each layer has 9 cubes','हर परत में 9 cubes'],['There are 3 layers','3 परतें हैं'],['It contains 9 cubes in total','कुल 9 cubes हैं'],['It contains 27 cubes in total','कुल 27 cubes हैं']],['A','B','D'],'There are 3 layers with 9 cubes each: 3 × 9 = 27.','9 cubes की 3 परतें हैं: 3 × 9 = 27।');
  fill(7,'5³ = ___.','5³ = ___।',125,'5 × 5 × 5 = 125.','5 × 5 × 5 = 125।');
  fill(7,'Doubling a cube’s side multiplies its volume by ___.','Cube की side दोगुनी करने पर volume ___ गुना होता है।',8,'Each of 3 directions doubles: 2 × 2 × 2 = 8.','तीनों दिशाएँ दोगुनी: 2 × 2 × 2 = 8।');
  match(7,[['2³','2³','8','8'],['4³','4³','64','64'],['6³','6³','216','216']],'Multiply each base three times as a factor.','हर base को तीन बार factor के रूप में गुणा कीजिए।');
  written(7,'A child counts only 16 cubes on the front of a 4 × 4 × 4 stack. Explain how to count every cube.','बच्चा 4 × 4 × 4 ढेर के सामने सिर्फ 16 cubes गिनता है। पूरे cubes कैसे गिनेंगे?','The front corresponds to one 4 × 4 layer with 16 cubes. There are 4 layers in depth, so the total is 16 × 4 = 64. Count hidden layers too.','सामने 4 × 4 की एक परत है, जिसमें 16 cubes हैं। गहराई में ऐसी 4 परतें हैं, इसलिए कुल 16 × 4 = 64। छिपी परतें भी गिनिए।',[['Identify one layer as 16.','एक परत में 16 पहचाने।'],['Include all 4 layers.','चारों परतें शामिल कीं।'],['Conclude 64, not 16.','16 नहीं, 64 बताया।']]);
  mc(8,'∛343 equals…','∛343 बराबर है…',[o('7'),o('49'),o('114.33'),o('−7')],'A','7 × 7 × 7 = 343.','7 × 7 × 7 = 343।');
  mc(8,'For a cube root, equal prime factors are grouped in…','Cube root में बराबर prime factors के समूह में कितने होते हैं?',[o('2'),o('3'),o('4'),o('6')],'B','Cubing uses three equal factors, so undo it with triples.','Cube में तीन बराबर factors हैं, इसलिए उल्टी क्रिया में triples लीजिए।');
  mc(8,'∛(−64) equals…','∛(−64) बराबर है…',[o('4'),o('−4'),o('8'),o('−8')],'B','(−4) × (−4) × (−4) = −64.','(−4) × (−4) × (−4) = −64।');
  multi(8,'Choose ALL correct roots.','सभी सही roots चुनिए।',[o('∛8 = 2'),o('∛125 = 5'),o('∛64 = 8'),o('∛1000 = 10')],['A','B','D'],'2³ = 8, 5³ = 125 and 10³ = 1000. ∛64 is 4; √64 is 8.','2³ = 8, 5³ = 125 और 10³ = 1000। ∛64, 4 है; √64, 8 है।');
  fill(8,'∛729 = ___.','∛729 = ___।',9,'9 × 9 × 9 = 729.','9 × 9 × 9 = 729।');
  fill(8,'A cube has volume 512 cm³. Its edge is ___ cm.','Cube का volume 512 cm³ है। Edge ___ cm है।',8,'8³ = 512, so ∛512 = 8.','8³ = 512, इसलिए ∛512 = 8।');
  match(8,[['∛27','∛27','3','3'],['∛216','∛216','6','6'],['∛(−125)','∛(−125)','−5','−5']],'Cube each partner to check the match.','हर साथी का cube करके मिलान जाँचिए।');
  written(8,'Why are √64 and ∛64 different? Explain with prime groups.','√64 और ∛64 अलग क्यों हैं? Prime समूहों से समझाइए।','64 = 2⁶. For √64, make 3 pairs and take 2 × 2 × 2 = 8. For ∛64, make 2 triples and take 2 × 2 = 4. Check 8² = 64 and 4³ = 64.','64 = 2⁶। √64 में 3 जोड़ियों से 2 × 2 × 2 = 8। ∛64 में 2 triples से 2 × 2 = 4। जाँच: 8² = 64 और 4³ = 64।',[['Write six factors of 2.','2 के छह factors लिखे।'],['Distinguish pairs and triples.','जोड़ियों और triples का अंतर बताया।'],['Check both roots.','दोनों roots जाँचे।']]);
  mc(9,'Smallest positive whole-number multiplier making 108 a cube?','108 को cube बनाने वाला सबसे छोटा धनात्मक whole-number multiplier?',[o('2'),o('3'),o('4'),o('6')],'A','108 = 2² × 3³ needs one more 2; 108 × 2 = 216.','108 = 2² × 3³ में एक और 2 चाहिए; 108 × 2 = 216।');
  mc(9,'Smallest positive whole number to divide 72 by to get a cube?','72 को cube बनाने के लिए सबसे छोटी किस धनात्मक whole number से भाग दें?',[o('2'),o('3'),o('9'),o('24')],'C','72 = 2³ × 3². Remove 3² = 9 to leave 8.','72 = 2³ × 3²। 3² = 9 हटाने पर 8 बचेगा।');
  mc(9,'How many blocks must be ADDED to 72 to reach 216?','72 से 216 तक पहुँचने के लिए कितने blocks जोड़ने होंगे?',[o('3'),o('9'),o('144'),o('288')],'C','Addition asks for the difference: 216 − 72 = 144.','जोड़ने के लिए अंतर खोजिए: 216 − 72 = 144।');
  multi(9,'Choose ALL numbers that are both perfect squares and perfect cubes.','वे सभी संख्याएँ चुनिए जो perfect square और perfect cube दोनों हैं।',[o('1'),o('64'),o('36'),o('729')],['A','B','D'],'1 = 1² = 1³; 64 = 8² = 4³; 729 = 27² = 9³. 36 is not a cube.','1 = 1² = 1³; 64 = 8² = 4³; 729 = 27² = 9³। 36 cube नहीं है।');
  fill(9,'Smallest positive whole-number multiplier making 250 a cube = ___.','250 को cube बनाने वाला सबसे छोटा धनात्मक whole-number multiplier = ___।',4,'250 = 2 × 5³. Supply two more twos: multiply by 4 to get 1000.','250 = 2 × 5³। दो और twos चाहिए: 4 से गुणा करने पर 1000।');
  fill(9,'Smallest positive whole number to divide 108 by to get a cube = ___.','108 को cube बनाने के लिए सबसे छोटी धनात्मक whole number जिससे भाग दें = ___।',4,'108 = 2² × 3³. Divide by 4 to get 27.','108 = 2² × 3³। 4 से भाग देने पर 27।');
  match(9,[['16 × ? is a cube (least positive whole multiplier)','16 × ? cube है (सबसे छोटा धनात्मक whole multiplier)','4','4'],['32 × ? is a cube (least positive whole multiplier)','32 × ? cube है (सबसे छोटा धनात्मक whole multiplier)','2','2'],['25 × ? is a cube (least positive whole multiplier)','25 × ? cube है (सबसे छोटा धनात्मक whole multiplier)','5','5']],'16 × 4 = 64; 32 × 2 = 64; 25 × 5 = 125. Each multiplier completes prime triples.','16 × 4 = 64; 32 × 2 = 64; 25 × 5 = 125। हर multiplier prime triples पूरे करता है।');
  written(9,'Find both the smallest positive whole-number multiplier and divisor that make 500 a perfect cube.','500 को perfect cube बनाने वाले सबसे छोटे धनात्मक whole-number multiplier और divisor दोनों खोजिए।','500 = 2² × 5³. Multiply by 2 to get 1000 = 10³. Divide by 4 to get 125 = 5³. Multiplication completes the pair of twos; division removes it.','500 = 2² × 5³। 2 से गुणा पर 1000 = 10³। 4 से भाग पर 125 = 5³। गुणा twos का triple पूरा करता है; भाग अधूरा समूह हटाता है।',[['Factorise 500 correctly.','500 का सही factorisation किया।'],['Find and check multiplier 2.','Multiplier 2 खोजा और जाँचा।'],['Find and check divisor 4.','Divisor 4 खोजा और जाँचा।']]);
  mc(10,'A square garden has area 196 m². Its side is…','Square बगीचे का area 196 m² है। Side है…',[o('14 m'),o('49 m'),o('98 m'),o('196 m')],'A','14² = 196, so the side is 14 m.','14² = 196, इसलिए side 14 m है।');
  mc(10,'A cube-shaped box has volume 729 cm³. Its edge is…','Cube-shaped box का volume 729 cm³ है। Edge है…',[o('27 cm'),o('9 cm'),o('243 cm'),o('81 cm')],'B','Use cube root: 9³ = 729.','Cube root लीजिए: 9³ = 729।');
  mc(10,'A square of side 10 m needs fencing on all four sides at ₹15/m. Cost?','10 m side वाले square की चारों sides पर ₹15/m की बाड़ का खर्च?',[o('₹150'),o('₹400'),o('₹600'),o('₹1500')],'C','Perimeter = 40 m, so cost = 40 × 15 = ₹600.','Perimeter = 40 m, इसलिए खर्च = 40 × 15 = ₹600।');
  multi(10,'Which pairs of quantity and unit are correct? Choose ALL.','Quantity और unit की सभी सही जोड़ियाँ चुनिए।',[['Garden area — m²','बगीचे का area — m²'],['Fence length — m','बाड़ की लंबाई — m'],['Box volume — cm³','Box का volume — cm³'],['Garden side — m²','बगीचे की side — m²']],['A','B','C'],'Area uses square units, length uses linear units, volume uses cubic units.','Area में square units, लंबाई में साधारण units, volume में cubic units।');
  fill(10,'A square garden has area 225 m². Its full perimeter is ___ m.','Square बगीचे का area 225 m² है। पूरा perimeter ___ m है।',60,'Side = √225 = 15 m; perimeter = 4 × 15 = 60 m.','Side = √225 = 15 m; perimeter = 4 × 15 = 60 m।');
  fill(10,'A cube-shaped box has edge 7 cm. Its volume is ___ cm³.','Cube-shaped box की edge 7 cm है। Volume ___ cm³ है।',343,'7 × 7 × 7 = 343.','7 × 7 × 7 = 343।');
  match(10,[['Side from square area','Square area से side','Square root','Square root'],['Edge from cube volume','Cube volume से edge','Cube root','Cube root'],['Fence around a square','Square के चारों ओर बाड़','4 × side','4 × side']],'Choose the operation using the meaning of the quantity.','Quantity का मतलब देखकर क्रिया चुनिए।');
  written(10,'Plan fencing for a square garden of area 256 m² at ₹25/m. Also find the edge of a 343 cm³ cube model. Show checks and assumptions.','256 m² square बगीचे की ₹25/m पर बाड़ की योजना बनाइए। 343 cm³ cube model की edge भी खोजिए। जाँच और शर्तें बताइए।','Garden side = √256 = 16 m. Perimeter = 64 m. Cost = 64 × 25 = ₹1600, assuming no gate, wastage or labour charges. Model edge = ∛343 = 7 cm. Checks: 16² = 256 and 7³ = 343.','बगीचे की side = √256 = 16 m। Perimeter = 64 m। खर्च = 64 × 25 = ₹1600; gate, wastage और मजदूरी नहीं जोड़ी। Model edge = ∛343 = 7 cm। जाँच: 16² = 256 और 7³ = 343।',[['Calculate side, perimeter and cost with units.','Side, perimeter और खर्च units के साथ निकाले।'],['Use cube root for the model and check it.','Model में cube root लिया और जाँचा।'],['State fencing assumptions.','बाड़ की शर्तें बताईं।']]);

  var ch={no:1,label:b('Pilot chapter','पायलट अध्याय'),name:b('A Square and a Cube','Square और Cube — वर्ग और घन'),topics:topics,
    checkpoint:b('10 small lessons · 80 questions. Learn in order, or revisit a topic. Written responses use a model and self-review, not automatic marks.','10 छोटे पाठ · 80 प्रश्न। क्रम से सीखिए या कोई topic दोहराइए। लिखित उत्तर में model और self-review है, automatic अंक नहीं।'),
    summary:b('**Square and square root**\nSide × side = area. √area gives a square’s non-negative side. Use prime pairs or digit pairs for roots. Estimate with neighbouring squares.\n\n**Patterns**\nGrowing n to n + 1 adds 2n + 1. Allowed last digits do not prove a square.\n\n**Cube and cube root**\nSide × side × side = volume. ∛volume gives the cube’s side. Group equal primes in threes.\n\n**Complete or remove**\nMultiplication supplies missing factors; division removes incomplete groups. Read the operation carefully.\n\n**Communicate**\nWrite your method, units and a multiplication check. For a real plan, state assumptions.\n\n**Readiness check**\nCan you explain 6² versus 6³? Can you find √144 and ∛216? Can you reject √80 = 40? If not, revisit the relevant micro-topic before the assignment.',
    '**Square और square root**\nSide × side = area। √area से square की non-negative side मिलती है। Roots के लिए prime जोड़ियाँ या digit pairs लीजिए। पड़ोसी squares से अंदाज़ा लगाइए।\n\n**Patterns**\nn से n + 1 बढ़ने पर 2n + 1 जुड़ता है। सही आखिरी digit, square होने का प्रमाण नहीं है।\n\n**Cube और cube root**\nSide × side × side = volume। ∛volume से cube की side मिलती है। बराबर primes के तीन-तीन समूह बनाइए।\n\n**पूरा करें या हटाएँ**\nगुणा से missing factors मिलते हैं। भाग से अधूरे समूह हटते हैं। क्रिया ध्यान से पढ़िए।\n\n**समझाकर लिखिए**\nतरीका, units और गुणा से जाँच लिखिए। असली योजना में शर्तें भी बताइए।\n\n**तैयारी जाँच**\n6² और 6³ का अंतर समझा सकते हैं? √144 और ∛216 खोज सकते हैं? √80 = 40 को गलत बता सकते हैं? नहीं तो असाइनमेंट से पहले वह micro-topic दोहराइए।'),
    assignment:b('**School design challenge · 25–35 minutes**\nMaterials: squared paper, pencil, ruler; optional large paper blocks. No purchases needed.\n\n1. Draw a square courtyard patch of area 64 m² at a scale of 1 cm for 1 m. Label the side and perimeter.\n2. Enlarge it to side 9 m. Colour only the new border. Count its extra square units.\n3. Fence the new patch at ₹20/m with a 1 m gate opening. Find the fence length and cost, ignoring waste and labour.\n4. Sketch a cube model of volume 125 cm³ as separate square layers. Label the edge, number of layers and blocks per layer.\n5. Write one paragraph explaining why the courtyard needs a square root and the model needs a cube root.\n\n**Check after attempting**\n1. Side 8 m, perimeter 32 m; draw an 8 cm square.\n2. Extra area = 81 − 64 = 17 m².\n3. Perimeter 36 m; subtract the gate: 35 m of fence, cost ₹700.\n4. Edge 5 cm; five layers with 25 unit cubes per layer, total 125.\n5. Area multiplies two equal lengths; cube volume multiplies three.\n\n**Explain and reflect**\nShow someone your labelled drawings. Ask them to check your units. What did your first attempt miss? Keep your paper or a photo; this activity is not uploaded automatically.',
    '**स्कूल design challenge · 25–35 मिनट**\nसामान: squared कागज़, pencil, ruler; चाहें तो बड़े paper blocks। कुछ खरीदना ज़रूरी नहीं।\n\n1. 64 m² का square आँगन बनाइए। Scale: 1 m के लिए 1 cm। Side और perimeter लिखिए।\n2. Side बढ़ाकर 9 m कीजिए। सिर्फ नया किनारा रंगिए। नई square units गिनिए।\n3. नई जगह पर ₹20/m की बाड़ लगाइए, 1 m का gate खुला छोड़िए। Wastage और मजदूरी छोड़कर लंबाई और खर्च खोजिए।\n4. 125 cm³ cube model की अलग-अलग square परतें बनाइए। Edge, परतों की संख्या और हर परत के blocks लिखिए।\n5. समझाइए कि आँगन में square root और model में cube root क्यों चाहिए।\n\n**कोशिश के बाद जाँचें**\n1. Side 8 m, perimeter 32 m; कागज़ पर 8 cm square।\n2. नया area = 81 − 64 = 17 m²।\n3. Perimeter 36 m; gate घटाकर 35 m बाड़, खर्च ₹700।\n4. Edge 5 cm; 25 unit cubes की पाँच परतें, कुल 125।\n5. Area में दो बराबर लंबाइयाँ और cube volume में तीन गुणा होती हैं।\n\n**समझाइए और सोचिए**\nअपने labelled चित्र किसी को दिखाइए। Units जँचवाइए। पहली कोशिश में क्या छूटा? कागज़ या photo रखें; यह activity अपने आप upload नहीं होती।'),
    assessment:qs.filter(function(x,i){return i%8===2||i%8===3;}).map(function(x){return x.id;}),
    revision:qs.filter(function(x,i){return i%8===4;}).map(function(x){return x.id;})};
  window.SL_DATA.subjects.push({code:'MATH8',board:'JAC/CBSE',klass:8,icon:'🧩',name:b('Mathematics · Class 8','गणित · कक्षा 8'),
    intro:b('**Build it. Explain it. Try it.**\nThis pilot chapter explores squares, square roots, cubes and cube roots through tiles, patterns and school planning. Start with multiplication and division; revise prime factors if needed. Each micro-topic has a bilingual audio explanation, an interactive visual, a worked example and eight questions.\n\n**A manageable rhythm**\nSpend 10–15 minutes on one micro-topic. Predict before moving a control. Say the idea aloud, then practise. Repeat when you need to; speed is not the goal.\n\n**Board alignment**\nThe pilot maps conceptually to NCERT Grade 8 Ganita Prakash Part I, Chapter 1, A Square and a Cube (2026–27 reprint), with extra root-method practice. JAC learners can use these number skills, but the current JAC textbook edition and chapter sequence still need teacher confirmation. This is original supplementary teaching, not a claim of full textbook or exam coverage.\n\n**Audio and written work**\nAudio is generated by your browser’s installed voices, not a human recording. Voice availability and quality vary by device. Every script is also readable. Written answers are self-reviewed against a model and rubric, and are kept separate from automatically scored questions.',
    '**बनाइए। समझाइए। करके देखिए।**\nइस पायलट chapter में टाइलों, patterns और स्कूल की योजनाओं से squares, square roots, cubes और cube roots सीखेंगे। गुणा और भाग आना चाहिए; ज़रूरत हो तो prime factors दोहराइए। हर micro-topic में दो भाषाओं का audio, interactive चित्र, worked example और आठ प्रश्न हैं।\n\n**आराम से सीखने का तरीका**\nएक micro-topic पर 10–15 मिनट दीजिए। Control बदलने से पहले अंदाज़ा लगाइए। बात ज़ोर से समझाइए, फिर अभ्यास कीजिए। ज़रूरत पर दोहराइए; तेज़ी लक्ष्य नहीं है।\n\n**Board से संबंध**\nयह पायलट NCERT Grade 8 Ganita Prakash Part I के Chapter 1, A Square and a Cube (2026–27 reprint) की अवधारणाओं से जुड़ा है। Roots के तरीकों का अतिरिक्त अभ्यास भी है। JAC के विद्यार्थी ये skills सीख सकते हैं, लेकिन वर्तमान JAC पुस्तक और chapter क्रम की शिक्षक से पुष्टि बाकी है। यह मौलिक सहायक पाठ है; पूरे textbook या परीक्षा coverage का दावा नहीं।\n\n**Audio और लिखित काम**\nAudio आपके browser की आवाज़ों से बनता है, human recording नहीं है। Device के अनुसार आवाज़ मिलना और उसकी गुणवत्ता बदल सकती है। हर script पढ़ भी सकते हैं। लिखित उत्तर model और rubric से खुद जाँचे जाते हैं; automatic score से अलग रहते हैं।'),chapters:[ch]});
  Array.prototype.push.apply(window.SL_DATA.questions,qs);
}());
