(() => {
 'use strict';
 const data=window.SELFLEARN_EXTERNAL_COURSES,courses=data?.courses||[];
 const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
 const labels={
  en:{eyebrow:'LEARN BEYOND SELFLEARN',title:'External courses',intro:'Explore CBSE and Jharkhand school courses, national government exam preparation and job skills. Compare the details, then check the provider page before enrolling.',skillPathwaysEyebrow:'SKILL INDIA SOURCES',skillPathwaysTitle:'Explore more skill pathways',skillPathwaysIntro:'NSDC lists online courses through eSkill India and free learning resources, including Hindi tailoring videos. Browse current options directly on these official sites.',eskillLink:'NSDC eSkill India ↗',nsdcResourcesLink:'NSDC free learning resources ↗',browseEyebrow:'COURSE DIRECTORY',browseTitle:'Find a course',search:'Search courses',searchHint:'Course, subject or provider',focus:'Subject / focus',board:'School board',language:'Teaching language',eligibility:'Eligibility / learner level',duration:'Duration',fee:'Fee',mode:'Online / offline',reset:'Clear filters',empty:'No courses match these filters. Try clearing one or more selections.',footer:'External listings link to their providers. Prices, availability and refund terms can change.',checked:'Course details checked',results:n=>`${n} ${n===1?'course':'courses'}`,all:'All courses',school:'School subjects',government:'Govt. job preparation',skills:'Skill courses',any:'Any',open:'Open to beginners',class9:'Class 9 learners',class10:'Class 10 learners',class12:'Class 12 / 10+2 target',graduate:'Graduate-level exam target',selfPaced:'Self-paced',short:'Under 6 months',long:'6+ months',free:'Free',under1000:'Under ₹1,000',midFee:'₹1,000–₹5,000',over5000:'Over ₹5,000',unlisted:'Fee not listed',online:'Online',offline:'Offline',audience:'Eligibility / learner',boardFact:'Board',languageFact:'Language',durationFact:'Duration',feeFact:'Fee',modeFact:'Mode',covers:'What you study',prospect:'Possible next step',provider:'View provider course',source:'Listing source'},
  hi:{eyebrow:'SELFLEARN से आगे सीखें',title:'बाहरी पाठ्यक्रम',intro:'CBSE और झारखंड के स्कूल पाठ्यक्रम, राष्ट्रीय सरकारी परीक्षाओं और नौकरी के कौशल के कोर्स देखें। विवरण की तुलना करें और प्रवेश से पहले संस्था की वेबसाइट जाँचें।',skillPathwaysEyebrow:'SKILL INDIA स्रोत',skillPathwaysTitle:'और कौशल पाठ्यक्रम खोजें',skillPathwaysIntro:'NSDC के eSkill India पर ऑनलाइन पाठ्यक्रम और मुफ़्त अध्ययन सामग्री मिलती है, जिसमें हिंदी सिलाई वीडियो भी हैं। उपलब्ध विकल्प आधिकारिक साइटों पर देखें।',eskillLink:'NSDC eSkill India ↗',nsdcResourcesLink:'NSDC मुफ़्त अध्ययन सामग्री ↗',browseEyebrow:'पाठ्यक्रम सूची',browseTitle:'पाठ्यक्रम खोजें',search:'पाठ्यक्रम खोजें',searchHint:'पाठ्यक्रम, विषय या संस्था',focus:'विषय / क्षेत्र',board:'स्कूल बोर्ड',language:'पढ़ाने की भाषा',eligibility:'पात्रता / विद्यार्थी स्तर',duration:'अवधि',fee:'शुल्क',mode:'ऑनलाइन / ऑफलाइन',reset:'फ़िल्टर हटाएँ',empty:'इन फ़िल्टरों से कोई पाठ्यक्रम नहीं मिला। कुछ फ़िल्टर हटाकर देखें।',footer:'बाहरी पाठ्यक्रमों के लिंक संबंधित संस्थाओं की वेबसाइट पर जाते हैं। शुल्क, उपलब्धता और रिफ़ंड की शर्तें बदल सकती हैं।',checked:'पाठ्यक्रम विवरण जाँचे गए',results:n=>`${n} पाठ्यक्रम`,all:'सभी पाठ्यक्रम',school:'स्कूल विषय',government:'सरकारी नौकरी की तैयारी',skills:'कौशल पाठ्यक्रम',any:'कोई भी',open:'शुरुआती भी कर सकते हैं',class9:'कक्षा 9 के विद्यार्थी',class10:'कक्षा 10 के विद्यार्थी',class12:'कक्षा 12 / 10+2 स्तर',graduate:'स्नातक स्तर की परीक्षा',selfPaced:'अपनी गति से',short:'6 महीने से कम',long:'6+ महीने',free:'निःशुल्क',under1000:'₹1,000 से कम',midFee:'₹1,000–₹5,000',over5000:'₹5,000 से अधिक',unlisted:'शुल्क नहीं दिया गया',online:'ऑनलाइन',offline:'ऑफलाइन',audience:'पात्रता / किसके लिए',boardFact:'बोर्ड',languageFact:'भाषा',durationFact:'अवधि',feeFact:'शुल्क',modeFact:'माध्यम',covers:'क्या सीखेंगे',prospect:'आगे का संभावित रास्ता',provider:'संस्था की वेबसाइट देखें',source:'सूची का स्रोत'}
 };
 Object.assign(labels.en,{corporateEyebrow:'FREE COMPANY COURSES',corporateTitle:'Learn from technology companies',corporateIntro:'Explore free training from Google, Microsoft, IBM, Canva, Cisco, SOLIDWORKS and more. Some software, exams or advanced features can cost extra; each listing explains the distinction.',corporateButton:'Browse free company courses ↓',providerType:'Provider type',companies:'Company courses',otherProviders:'Other providers'});
 Object.assign(labels.hi,{corporateEyebrow:'कंपनियों के मुफ़्त कोर्स',corporateTitle:'तकनीकी कंपनियों से सीखें',corporateIntro:'Google, Microsoft, IBM, Canva, Cisco, SOLIDWORKS और अन्य कंपनियों के मुफ़्त पाठ्यक्रम देखें। कुछ सॉफ़्टवेयर, परीक्षाओं या उन्नत सुविधाओं का अलग शुल्क हो सकता है; हर सूची में यह स्पष्ट है।',corporateButton:'कंपनियों के मुफ़्त कोर्स देखें ↓',providerType:'पाठ्यक्रम देने वाला',companies:'कंपनियों के कोर्स',otherProviders:'अन्य संस्थाएँ'});
 let lang=localStorage.getItem('sl_lang')==='hi'?'hi':'en',category=new URLSearchParams(location.search).get('category')||'all';
 if(!['all','school','government','skills'].includes(category))category='all';
 const filters={search:$('search'),providerType:$('provider-type'),focus:$('focus'),board:$('board'),language:$('language'),eligibility:$('eligibility'),duration:$('duration'),fee:$('fee'),mode:$('mode')};
 const option=(value,label)=>`<option value="${esc(value)}">${esc(label)}</option>`;
 function fillOptions(){const t=labels[lang],old=Object.fromEntries(Object.entries(filters).filter(([key])=>key!=='search').map(([key,field])=>[key,field.value]));
  const focuses=[...new Set(courses.filter(c=>category==='all'||c.category===category).map(c=>c.focus))].sort();
  filters.providerType.innerHTML=option('',t.any)+option('corporate',t.companies)+option('other',t.otherProviders);
  filters.focus.innerHTML=option('',t.any)+focuses.map(f=>option(f,f)).join('');
  filters.board.innerHTML=option('',t.any)+option('CBSE','CBSE')+option('JAC','JAC (Jharkhand)');
  filters.language.innerHTML=option('',t.any)+['Hindi','English','Hinglish'].map(value=>option(value,value)).join('');
  filters.eligibility.innerHTML=option('',t.any)+[['open',t.open],['class9',t.class9],['class10',t.class10],['class12',t.class12],['graduate',t.graduate]].map(pair=>option(...pair)).join('');
  filters.duration.innerHTML=option('',t.any)+option('short',t.short)+option('self-paced',t.selfPaced)+option('long',t.long);
  filters.fee.innerHTML=option('',t.any)+[['free',t.free],['under1000',t.under1000],['mid',t.midFee],['over5000',t.over5000],['unlisted',t.unlisted]].map(pair=>option(...pair)).join('');
  filters.mode.innerHTML=option('',t.any)+option('online',t.online)+option('offline',t.offline);
  for(const [key,value] of Object.entries(old))if([...filters[key].options].some(o=>o.value===value))filters[key].value=value;
 }
 function categoryButtons(){const t=labels[lang];$('categories').innerHTML=[['all',t.all],['school',t.school],['government',t.government],['skills',t.skills]].map(([key,label])=>`<button type="button" data-category="${key}" aria-pressed="${category===key}">${esc(label)}</button>`).join('');$('categories').querySelectorAll('button').forEach(button=>button.onclick=()=>{category=button.dataset.category;const url=new URL(location.href);if(category==='all')url.searchParams.delete('category');else url.searchParams.set('category',category);history.replaceState(null,'',url);filters.focus.value='';fillOptions();categoryButtons();render()})}
 function feeMatches(course,band){if(filters.providerType.value==='corporate'&&course.providerType!=='corporate')return false;if(filters.providerType.value==='other'&&course.providerType==='corporate')return false;const value=course.feeINR;if(!band)return true;if(band==='unlisted')return value===null;if(value===null)return false;if(band==='free')return value===0;if(band==='under1000')return value>0&&value<1000;if(band==='mid')return value>=1000&&value<=5000;return value>5000}
 function matches(course){const q=filters.search.value.trim().toLocaleLowerCase();return(category==='all'||course.category===category)&&(!q||[course.title,course.provider,course.focus,course.covers,course.summary,course.board||'',course.language.join(' ')].some(s=>s.toLocaleLowerCase().includes(q)))&&(!filters.focus.value||course.focus===filters.focus.value)&&(!filters.board.value||course.board===filters.board.value)&&(!filters.language.value||course.language.includes(filters.language.value))&&(!filters.eligibility.value||course.eligibility===filters.eligibility.value||course.eligibility==='open')&&(!filters.duration.value||course.durationBand===filters.duration.value)&&feeMatches(course,filters.fee.value)&&(!filters.mode.value||course.mode===filters.mode.value)}
 function card(course){const t=labels[lang],cat=t[course.category],mode=t[course.mode];return `<article class="course" data-course-id="${esc(course.id)}"><div class="course-top"><div><div class="provider">${esc(course.provider)}</div><h3>${esc(course.title)}</h3></div><span class="category-tag">${esc(cat)}</span></div><p class="course-summary">${esc(course.summary)}</p><dl class="facts"><div><dt>${esc(t.audience)}</dt><dd>${esc(course.audience)}</dd></div>${course.board?`<div><dt>${esc(t.boardFact)}</dt><dd>${esc(course.board==='JAC'?'JAC · Jharkhand':course.board)}</dd></div>`:''}<div><dt>${esc(t.languageFact)}</dt><dd>${esc(course.language.join(' / '))}</dd></div><div><dt>${esc(t.durationFact)}</dt><dd>${esc(course.duration)}</dd></div><div><dt>${esc(t.feeFact)}</dt><dd>${esc(course.fee)}</dd></div><div><dt>${esc(t.modeFact)}</dt><dd>${esc(mode)}</dd></div></dl><p class="course-detail"><strong>${esc(t.covers)}:</strong> ${esc(course.covers)}</p><p class="course-detail"><strong>${esc(t.prospect)}:</strong> ${esc(course.prospect)}</p><p class="fee-note">${esc(course.feeNote)}</p><div class="course-footer"><a class="course-link" href="${esc(course.url)}" target="_blank" rel="noopener noreferrer">${esc(t.provider)} ↗</a>${course.sourceUrl&&course.sourceUrl!==course.url?`<a class="source-link" href="${esc(course.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(t.source)} ↗</a>`:''}</div></article>`}
 function render(){const shown=courses.filter(matches),t=labels[lang];$('course-list').innerHTML=shown.map(card).join('');$('result-count').textContent=t.results(shown.length);$('empty-message').hidden=shown.length!==0}
 function translate(){const t=labels[lang];document.documentElement.lang=lang;document.title=`${t.title} · SelfLearn`;document.querySelectorAll('[data-text]').forEach(el=>el.textContent=t[el.dataset.text]);filters.search.placeholder=t.searchHint;$('checked-date').textContent=`${t.checked}: ${new Date(data.checkedAt+'T12:00:00').toLocaleDateString(lang==='hi'?'hi-IN':'en-IN',{day:'numeric',month:'long',year:'numeric'})}. ${t.footer}`;document.querySelectorAll('[data-lang]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.lang===lang)));fillOptions();categoryButtons();render()}
 $('course-filters').addEventListener('input',render);$('course-filters').addEventListener('change',render);$('course-filters').addEventListener('reset',event=>{event.preventDefault();filters.search.value='';for(const [key,field] of Object.entries(filters))if(key!=='search')field.value='';render()});document.querySelectorAll('[data-lang]').forEach(button=>button.onclick=()=>{lang=button.dataset.lang;localStorage.setItem('sl_lang',lang);translate()});translate();
})();
