/* Fictional learning data. Edit one sample price, then recheck cards and cart. */
const products=[
  {id:'rice',name:{en:'Rice',hi:'चावल'},category:'grocery',unit:{en:'1 kg',hi:'1 किलो'},price:60,inStock:true,icon:'🍚',color:'#ecf4da'},
  {id:'dal',name:{en:'Dal',hi:'दाल'},category:'grocery',unit:{en:'1 kg',hi:'1 किलो'},price:110,inStock:true,icon:'🫘',color:'#f8edce'},
  {id:'tomato',name:{en:'Tomatoes',hi:'टमाटर'},category:'vegetables',unit:{en:'1 kg',hi:'1 किलो'},price:30,inStock:true,icon:'🍅',color:'#fae7df'},
  {id:'potato',name:{en:'Potatoes',hi:'आलू'},category:'vegetables',unit:{en:'1 kg',hi:'1 किलो'},price:25,inStock:true,icon:'🥔',color:'#f2ecd7'},
  {id:'soap',name:{en:'Soap',hi:'साबुन'},category:'household',unit:{en:'1 bar',hi:'1 टिकिया'},price:35,inStock:true,icon:'🧼',color:'#e2eef8'},
  {id:'detergent',name:{en:'Detergent',hi:'डिटर्जेंट'},category:'household',unit:{en:'1 pack',hi:'1 पैक'},price:80,inStock:false,icon:'🫧',color:'#e5f0f6'}
];
const copy={
  en:{brandTag:'A local market idea',cartNav:'Cart',eyebrow:'A SelfLearn build project',heroTitle:'Everyday finds, one local view.',heroText:'Explore a simple market catalog, practise search and plan a basket before a visit.',browse:'Browse sample items ↓',demoNote:'Learning demo: all products, prices and availability are fictional. No orders or payments are taken.',shopLabel:'EXPLORE THE MARKET',catalogTitle:'Sample products',searchLabel:'Search items',sortLabel:'Sort by',featured:'Featured',low:'Price: low to high',high:'Price: high to low',all:'All',grocery:'Grocery',vegetables:'Vegetables',household:'Household',items:'items',item:'item',add:'Add',unavailable:'Unavailable',emptyTitle:'No matching items',emptyText:'Try another word or return to all categories.',clear:'Clear filters',basketLabel:'PRACTICE BASKET',cartTitle:'Your cart',cartEmpty:'Add a sample item to see your basket.',total:'Estimated total',cartNotice:'Practice only — no order placed. Confirm real prices and stock directly with sellers.',remove:'Remove',nextLabel:'KEEP IMPROVING',nextTitle:'One useful change each day',step1:'Hear one customer or seller need.',step2:'Ask the coding assistant for a small change.',step3:'Inspect, preview and test before keeping it.',footer:'An original SelfLearn practice project for a possible Satbarwa market website. Not affiliated with any retailer or real seller.',searchPlaceholder:'e.g. rice, dal'},
  hi:{brandTag:'स्थानीय बाज़ार का विचार',cartNav:'टोकरी',eyebrow:'SelfLearn का build project',heroTitle:'रोज़ की ज़रूरतें, एक स्थानीय जगह।',heroText:'Sample बाज़ार देखें, चीज़ें खोजें और आने से पहले अपनी टोकरी plan करें।',browse:'Sample सामान देखें ↓',demoNote:'अभ्यास demo: सभी products, prices और availability काल्पनिक हैं। यहाँ order या payment नहीं होता।',shopLabel:'बाज़ार देखें',catalogTitle:'Sample products',searchLabel:'सामान खोजें',sortLabel:'क्रम चुनें',featured:'सामान्य क्रम',low:'Price: कम से अधिक',high:'Price: अधिक से कम',all:'सभी',grocery:'किराना',vegetables:'सब्ज़ियाँ',household:'घर का सामान',items:'items',item:'item',add:'जोड़ें',unavailable:'अभी उपलब्ध नहीं',emptyTitle:'कोई सामान नहीं मिला',emptyText:'दूसरा शब्द खोजें या सभी categories दिखाएँ।',clear:'Filters हटाएँ',basketLabel:'अभ्यास टोकरी',cartTitle:'आपकी टोकरी',cartEmpty:'टोकरी देखने के लिए sample सामान जोड़ें।',total:'अनुमानित कुल',cartNotice:'केवल अभ्यास — order नहीं दिया गया। असली price और stock सीधे दुकानदार से जाँचें।',remove:'हटाएँ',nextLabel:'रोज़ सुधारें',nextTitle:'हर दिन एक उपयोगी बदलाव',step1:'ग्राहक या दुकानदार की एक ज़रूरत सुनें।',step2:'Coding assistant से छोटा बदलाव माँगें।',step3:'बदलाव रखने से पहले देखें, preview करें और जाँचें।',footer:'संभावित Satbarwa बाज़ार website के लिए SelfLearn का मौलिक अभ्यास project। किसी retailer या असली seller से जुड़ा नहीं।',searchPlaceholder:'जैसे चावल, दाल'}
};
const state={lang:'en',category:'all',query:'',sort:'featured',cart:{}};
const money=n=>'₹'+new Intl.NumberFormat('en-IN').format(n);
const el=id=>document.getElementById(id);
function text(key){return copy[state.lang][key];}
function loadCart(){try{const saved=JSON.parse(localStorage.getItem('satbarwa_demo_cart')||'{}');for(const [id,qty] of Object.entries(saved)){const p=products.find(x=>x.id===id);if(p&&p.inStock&&Number.isInteger(qty)&&qty>0&&qty<=99)state.cart[id]=qty;}}catch(_){state.cart={};}}
function saveCart(){try{localStorage.setItem('satbarwa_demo_cart',JSON.stringify(state.cart));}catch(_){}}
function button(label,className,action){const b=document.createElement('button');b.type='button';b.className=className;b.textContent=label;b.addEventListener('click',action);return b;}
function renderStatic(){document.documentElement.lang=state.lang;document.querySelectorAll('[data-i18n]').forEach(node=>{node.textContent=text(node.dataset.i18n);});el('search').placeholder=text('searchPlaceholder');el('enBtn').setAttribute('aria-pressed',String(state.lang==='en'));el('hiBtn').setAttribute('aria-pressed',String(state.lang==='hi'));}
function renderCategories(){const box=el('categories');box.replaceChildren();['all','grocery','vegetables','household'].forEach(id=>{const b=button(text(id),'',()=>{state.category=id;renderAll();});b.setAttribute('aria-pressed',String(state.category===id));box.append(b);});}
function visibleProducts(){const q=state.query.trim().toLocaleLowerCase();let list=products.filter(p=>(state.category==='all'||p.category===state.category)&&(!q||p.name.en.toLocaleLowerCase().includes(q)||p.name.hi.includes(q)));if(state.sort==='low')list.sort((a,b)=>a.price-b.price);if(state.sort==='high')list.sort((a,b)=>b.price-a.price);return list;}
function renderProducts(){const list=visibleProducts(),grid=el('products');grid.replaceChildren();el('resultCount').textContent=list.length+' '+text(list.length===1?'item':'items');el('empty').hidden=list.length!==0;list.forEach(p=>{const article=document.createElement('article');article.className='product';const art=document.createElement('div');art.className='product-art';art.style.setProperty('--art',p.color);art.textContent=p.icon;art.setAttribute('aria-hidden','true');const body=document.createElement('div');body.className='product-body';const category=document.createElement('span');category.className='product-category';category.textContent=text(p.category);const title=document.createElement('h3');title.textContent=p.name[state.lang];const unit=document.createElement('p');unit.className='product-unit';unit.textContent=p.unit[state.lang];const bottom=document.createElement('div');bottom.className='product-bottom';const price=document.createElement('span');price.className='product-price';price.textContent=money(p.price);const add=button(p.inStock?text('add'):text('unavailable'),'add',()=>{state.cart[p.id]=Math.min(99,(state.cart[p.id]||0)+1);saveCart();renderCart();});add.disabled=!p.inStock;add.setAttribute('aria-label',(p.inStock?text('add')+' ':'')+p.name[state.lang]);bottom.append(price,add);body.append(category,title,unit,bottom);article.append(art,body);grid.append(article);});}
function renderCart(){const box=el('cartItems');box.replaceChildren();const entries=Object.entries(state.cart).filter(([,qty])=>qty>0);el('cartCount').textContent=String(entries.reduce((n,[,qty])=>n+qty,0));let total=0;if(!entries.length){const p=document.createElement('p');p.className='cart-empty';p.textContent=text('cartEmpty');box.append(p);}entries.forEach(([id,qty])=>{const product=products.find(p=>p.id===id);if(!product)return;total+=product.price*qty;const row=document.createElement('div');row.className='cart-row';const head=document.createElement('div');head.className='cart-row-head';const name=document.createElement('span');name.textContent=product.name[state.lang]+' ';const unit=document.createElement('small');unit.textContent=product.unit[state.lang];name.append(unit);const sum=document.createElement('strong');sum.textContent=money(product.price*qty);head.append(name,sum);const controls=document.createElement('div');controls.className='cart-row-controls';const quantity=document.createElement('div');quantity.className='quantity';const minus=button('−','',()=>changeQty(id,-1));minus.disabled=qty<=1;minus.setAttribute('aria-label',product.name[state.lang]+' −');const number=document.createElement('span');number.textContent=String(qty);const plus=button('+','',()=>changeQty(id,1));plus.disabled=qty>=99;plus.setAttribute('aria-label',product.name[state.lang]+' +');quantity.append(minus,number,plus);const remove=button(text('remove'),'remove',()=>{delete state.cart[id];saveCart();renderCart();});controls.append(quantity,remove);row.append(head,controls);box.append(row);});el('total').textContent=money(total);}
function changeQty(id,amount){const next=(state.cart[id]||0)+amount;if(next>=1&&next<=99){state.cart[id]=next;saveCart();renderCart();}}
function renderAll(){renderStatic();renderCategories();renderProducts();renderCart();}
el('enBtn').addEventListener('click',()=>{state.lang='en';renderAll();});
el('hiBtn').addEventListener('click',()=>{state.lang='hi';renderAll();});
el('search').addEventListener('input',event=>{state.query=event.target.value;renderProducts();});
el('sort').addEventListener('change',event=>{state.sort=event.target.value;renderProducts();});
el('clear').addEventListener('click',()=>{state.query='';state.category='all';el('search').value='';renderAll();el('search').focus();});
loadCart();renderAll();
